### ISSUE TITLE
Configure hook runs until timeout

### ISSUE THREAD

**Issue by jillro** [wekan/wekan-snap#10]
After a `snap install wekan` on fresh Ubuntu install (Scaleway C2S), the configure hook runs until timeout. CPU usage is very low. Finally, installation fails.

```bash
$ snap install wekan
error: cannot perform the following tasks:
- Run configure hook of "wekan" snap if present (run hook "configure": <exceeded maximum runtime of 5m0s>)
```

**Comment by xet7** [comment]
@guilro 

Do you have newest snapd and all updates installed ?

```
sudo apt update && sudo apt -y dist-upgrade
sudo reboot
```

You need to use sudo:

```
$ sudo snap install wekan
```

[Install info at wiki](https://github.com/wekan/wekan-snap/wiki/Install)

**Comment by jillro** [comment]
I have snap version 2.26.14 and I am logged as root.

**Comment by xet7** [comment]
What Ubuntu version is it?

```
cat /etc/issue
```

**Comment by jillro** [comment]
Ubuntu 16.04.2 LTS

**Comment by xet7** [comment]
And kernel version?

```
uname -a
```

**Comment by jillro** [comment]
Linux scw-8ad2d4 4.9.20-std-1 (bootscript by scaleway)

Other snaps install correctly.

**Comment by xet7** [comment]
Currently I have snapd 2.25 installed and Wekan works for me on 64bit Ubuntu 16.04.2.
https://launchpad.net/ubuntu/+source/snapd

Can you remove snapd and proposed repo and install snapd 2.25 from updates repo?

**Comment by jillro** [comment]
It still does not work with snap 2.25. If you cannot reproduce the bug, I will try to investigate further myself :) Thanks for your help.

**Comment by xet7** [comment]
Also see:

https://github.com/wekan/wekan-snap/issues/8#issuecomment-315737853

https://github.com/wekan/wekan-snap/issues/4#issuecomment-311355296

**Comment by kubiko** [comment]
Only thing I can think of is kernel not having all the patches snapd requires.
I'm not familiar with that kernel version or scw  platform. Ubuntu 16.04 should be running on 4.4 kernel. You probably need to contact whoever is maintaining that kernel and make sure all apparmor patches are up to date there….

**Comment by kubiko** [comment]
@guilro one thing to try to get more logs. Let's enable debugging from snapd
add to
` /etc/environment`
```
SNAPD_DEBUG=1
SNAPD_DEBUG_HTTP=7
```
then reboot or restart snapd

**Comment by jillro** [comment]
Surprisingly (I had already tried twice), I managed to make it run today with the exact same configuration. I will tell you if the problem happens again.

**Comment by kubiko** [comment]
@guilro then definitely enable debug if it comes back.
otherwise have you rebooted once you run all the distro updates? Problem is that snapd will re-exec once new version is installed but you are still running old kernel version, and then things stop working. reboot will eventually apply new kernel revision which will fix the things. Better error message could definitely help here
Out of curiosity have you kernel version changed since you checked and got version 'scw-8ad2d4 4.9.20-std-1'

**Comment by jillro** [comment]
Kernel version hasn't changed at all. I had already tried to reboot during my first attempts.
