### ISSUE TITLE
additional html file

### ISSUE THREAD

**Issue by stfnnnhfn** [wekan/wekan-snap#101]
Hi wekan-folks, 

is it possible to use some additional html and/or php tools on my wekan server ?
in which directory do I have to put them in ? 
I want to start it with (for example h t t p : / / 1 9 2 . . ./tools/sometool.php)

best regards and sorry for a absolute beginner issue
Stefan
wekan 3.21

**Comment by xet7** [comment]
Wekan Snap has Caddy. For http, add Caddyfile config this way:
```
http://192.168.x.x {
...
```
Enable Caddy:
```
sudo snap set wekan caddy-enabled='true'
```
See logs:
```
sudo snap logs wekan.caddy
```
You can also start or stop Wekan+Mongo+Caddy all this way:
```
sudo snap stop wekan
sudo snap start wekan
```
Caddy config is at `/var/snap/wekan/common/Caddyfile`

Add new files to some website subdirectory `/var/snap/wekan/common/mywebsite/`

Some examples:
https://github.com/caddyserver/examples

Some more Wekan Caddy info:
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

https://caddyserver.com/docs

Add comment to this issue if you don't get it working.

At Wekan GitHub wiki is also some examples of Apache, Nginx etc for Wekan, if you are more familiar with those webservers.

**Comment by xet7** [comment]
Because Snap is in secure sandbox, it can not access files outside of `/var/snap/wekan/common/` directory, that's why files need to be there.

**Comment by xet7** [comment]
If you use Docker or Source Wekan, then you don't have Caddy. You could just install for example Apache+PHP to some other port like `http://192.168.x.x:2000`
