### ISSUE TITLE
Rich text editor disabling

### ISSUE THREAD

**Issue by vjrj** [wekan/wekan-snap#104]
Does exist some way to disable the Rich text editor like in docker images?

I see that there is some `RICHER_CARD_COMMENT_EDITOR` variable, so I tried:
```
snap set wekan RICHER_CARD_COMMENT_EDITOR=false
error: cannot perform the following tasks:
- Run configure hook of "wekan" snap (invalid option name: "RICHER_CARD_COMMENT_EDITOR")
```
Without success.

Thanks

**Comment by xet7** [comment]
See snap settings at server:
```
wekan.help | less
```
Example:
```
sudo snap set wekan richer-card-comment-editor='false'
```

**Comment by vjrj** [comment]
Thanks as usual @xet7

**Comment by vjrj** [comment]
Hi @xet7, for some reason `sudo snap set wekan richer-card-comment-editor='false'` does not work with the last update. Any recommendation?

**Comment by vjrj** [comment]
I think is a regresion after this fix: https://github.com/wekan/wekan/commit/482682e50079d70c5113169020d6834013b57c11

**Comment by vjrj** [comment]
It's solved in the last release. Thanks
