### ISSUE TITLE
Snap restore db wiki error 

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan-snap#106]
Hi ! 

I cannot do a PR to change the wiki, so, I'm posting it as an issue.

To restore a db, the command written is : 
```
mongorestore --drop --port 27019
```
But, the new version of mongo asks to write the name of the db, the good command is : 
```
mongorestore -d wekan --drop --port 27019
```
This is the link of the wiki page : 
[https://github.com/wekan/wekan-snap/wiki/Backup-and-restore#stop-wekan-and-restore](https://github.com/wekan/wekan-snap/wiki/Backup-and-restore#stop-wekan-and-restore)

If you do not indicate the database name, you will have : 
```
don't know what to do with file "dump/unsaved-edits.metadata.json", skipping...
```
for each files.

Have a good day ;)

**Comment by xet7** [comment]
Thanks a lot ! I added it to wiki.

Wiki was previously editable by all GitHub users, but some newbies did not understand why it was editable, and posted some test pages, so I had to disable editing.
