### ISSUE TITLE
How to configure emails with Wekan snap and msmtp ?

### ISSUE THREAD

**Issue by CedricGoby** [wekan/wekan-snap#107]
Hi,

I plan to install Wekan with snap on a debian 10 server.
[msmtp](https://marlam.de/msmtp/msmtp.html) is installed on this server as Mail Transfer Agent.

Can I use msmtp to send email from Wekan snap ? And if yes how can I achieve this ?

Here is the msmtp config file /etc/msmtprc :

   account default
   host smtp.provider.com
   port 587
   auth on
   tls on
   tls_certcheck off
   from user@provider.com
   user user@provider.com
   password xxxxxxxxxxxx

Regards

**Comment by xet7** [comment]
Try this. Below `@` is urlencoded to `%40`
```
sudo snap set wekan mail-url="smtps://user%40provider.com:xxxxxx@smtp.provider.com:587"
sudo snap set wekan mail-from="Boards Support <user@provider.com>"
```
If it works, I recommend setting it up as cron at morning, see https://crontab.guru . This is just in case if that settings disappears for any reason.

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by CedricGoby** [comment]
I made a fresh install with snap and Apache.

I can access wekan using https://sub.domain.tld but I can't send email using "forgot password", I get "Internal server error" on the form 
![wekan-internal-server-error](https://user-images.githubusercontent.com/17612749/66042841-e3319300-e51d-11e9-9345-3693d45fdb15.png)

I have installed and configured msmtp as mentionned in my first post.
msmtp is correctly configured because I can send emails from the server using this command
`echo -e "Subject: Test Mail\r\n\r\nThis is a test mail" | msmtp -d -t recipient@domain.tld`

Then I send these commands (with special chars encoded in the password too)
`snap set wekan mail-url='smtps://user%40domain.tld:password@smtp.domain.tld:587'`
`snap set wekan mail-from='Wekan Boards <user@domain.tld>'`

Here is the log file when I try to ask for a new password :
`journalctl -u snap.wekan.wekan`
`oct. 02 13:38:41 my-wekan wekan.wekan[18306]: Exception while invoking method 'forgotPassword' { [object Object] code: 'ECONNECTION', command: 'CONN' }`

I noticed another error when I created the first user (the admin user)
`oct. 02 13:23:02 my-wekan wekan.wekan[18306]: Exception while invoking method 'ATCreateUserServer' { [object Object] code: 'ECONNECTION', command: 'CONN' }`

**Comment by xet7** [comment]
Hmm, I don't know does forgot password currently work https://github.com/wekan/wekan/issues/2020

**Comment by xet7** [comment]
You can change password at Admin Panel

**Comment by CedricGoby** [comment]
> Hmm, I don't know does forgot password currently work [wekan/wekan#2020](https://github.com/wekan/wekan/issues/2020)

So how can I check if wekan can send emails ?

And how is it possible that it's a one year bug ? 
I would like to use Wekan in a corporate environnement but it's not possible if people can't reset their password...

**Comment by xet7** [comment]
When I today tried forgot password on some server where Wekan email is configured correctly, it did say "Email sent".

So I think it's about your email settings.

I currently use AWS SES for sending email, my settings are here:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

There are various alternatives listed also at above URL.

**Comment by CedricGoby** [comment]
> So I think it's about your email settings.

Yes, I did not fill the form in the Admin Panel because I thought it was enough to send these commands.
`snap set wekan mail-url='smtps://user%40domain.tld:password@smtp.domain.tld:587'`
`snap set wekan mail-from='Wekan Boards <user@domain.tld>'`

Anyway everything works fine after I added these settings in the Admin Panel too
![wekan-ap-email-settings](https://user-images.githubusercontent.com/17612749/66061075-fef96100-e53e-11e9-85f8-6936eca8376f.png)

Thank you
