### ISSUE TITLE
Error when clicking on card when using localhost. Missing port in url.

### ISSUE THREAD

**Issue by karlsebal** [wekan/wekan-snap#108]
After creating a card in a list clicking on it will lead to an error: Cannot establish connection with 127.0.0.1. Reason is that the port 8080 is missing in the url. Every other action works. When adding port 8080 to the url manually everything works.

I installed wekan via ubuntu snap and the error can be reproduced on firefox and chromium both.

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='http://localhost:8080'
```
https://github.com/wekan/wekan/wiki/Settings

**Comment by karlsebal** [comment]
This should work out-of-the box, shouldn’t it? If default setting in a fresh install is 'localhost:8080' there should be no need to set it again from the command line. It is confusing that everything works except clicking on a card…
