### ISSUE TITLE
leaving mail settings unconfigured leads to errors instead of sending to stdout as stated in the docs

### ISSUE THREAD

**Issue by karlsebal** [wekan/wekan-snap#109]
As stated [in the docs](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#no-mail-server) I may leave email settings unconfigured but it does not work as expected.

I set up email settings in the frontend and sending emails worked well. After that I tried to remove the settings, which is not possible in the admin panel for it does not allow empty settings. I tried to set it via `snap set wekan mail-url=''; snap set wekan mail-from=''` and `snap wekan unset mail-url; snap wekan unset mail-from` respectively and it kind of worked for although in the gui I still have the data I entered before (I forced reload via ctrl-f5) sending a test email results in 

```
Sending email failed
Error trying to send email: getaddrinfo ENOTFOUND mailserver.examples.com mailserver.examples.com:25
```

Well that’s good in so far as the former settings seem to be deleted. But according to the docs emails should be sent to terminal output which is not the case. At least there is no output in `journalctl -u snap.wekan.wekan.service` and an error message is displayed

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses
