### ISSUE TITLE
Unable to move cards between lists by dragging

### ISSUE THREAD

**Issue by OpaqueArc** [wekan/wekan-snap#111]
I deployed my wekan instance by snap, and today it refuse to let me drag any card in any board to a different list.
>Ran snap refresh : all snaps are up to date
>Try "move card" option : works, but dragging still doesn't work
And also I didn't see the new "sort by" option on top of the board, did I do anything wrong?
Please reply if you need further details

**Comment by OpaqueArc** [comment]
Ehh apparently after a couple of restarts and letting it sit for like 10 mins, it magically fixed itself somehow.
Please close this issue if you feel like to

**Comment by chaserhkj** [comment]
I could confirm this bug on both of my snap wekan installations after they are automatically refreshed to the latest version 3.54 last night. And they are both working fine before the refresh.

Reverting to 3.53 by running `snap revert wekan` would do the trick to work around the issue, but apparently the latest 3.54 snap version has some bugs with it.

Edit: In addition to moving the cards, it seems that adding a card with the add button would not work with snap version 3.54 as well.

**Comment by chaserhkj** [comment]
Upstream issue: wekan/wekan#2814

**Comment by xet7** [comment]
Try Wekan v3.55
