### ISSUE TITLE
It is not possible to create comments in cards in the new release 3.54

### ISSUE THREAD

**Issue by kurgenal** [wekan/wekan-snap#112]
It is not possible to create comments in cards in the new release.
...
Name Version Rev Tracking Publisher Notes
core 16-2.42.1 8039 stable canonical✓ core
wekan 3.54 669 stable xet7 -

**Comment by chaserhkj** [comment]
#111  Seems to be related

Upstream issue: wekan/wekan#2814

**Comment by xet7** [comment]
Try Wekan v3.55
