### ISSUE TITLE
Mongodb keeps flooding syslog

### ISSUE THREAD

**Issue by fmeehan** [wekan/wekan-snap#113]
Hi, 

Mongodb in Wekan snap is flooding syslog with informational messages like the following:

> Nov 21 12:04:07 petrus mongod.27019[28761]: [conn4] received client metadata from 127.0.0.1:54784 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-70-generic" }, platform: "Node.js v8.16.2, LE, mongodb-core: 2.0.11" }

Can the log level can be change to suppress these messages?

Best regards, 

Francois Meehan

**Comment by xet7** [comment]
I don't know. You can look at MongoDB docs is there loglevel settings:
https://docs.mongodb.com/manual/

**Comment by fmeehan** [comment]
Hi, 

I don't see a way to modify mongodb server once started. 

File ``mongodb-control`` cannot be edited and that is were Mongodb is launched with the following command: 

```
mongod --dbpath /var/snap/wekan/common --syslog --journal --bind_ip 127.0.0.1 --port 27019 --smallfiles
```
There is a quiet setting; `` systemLog: verbosity: <int> quiet: <boolean>``,  to set in file mongod.conf, which I can't find under snap :-(

Francois

**Comment by xet7** [comment]
I'll try adding option `--quiet`.
https://jira.mongodb.org/browse/SERVER-18339

**Comment by elbaby** [comment]
FWIW, this doesn't seem to solve this problem.

I have snap version 956 (and I checked the --quiet option is there) and I keep getting 2 lines like these every 5 seconds:

```
Aug 27 11:52:10 cloud-j1 mongod.27019[126144]: [conn4] received client metadata from 127.0.0.1:60390 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:10 cloud-j1 mongod.27019[126144]: [conn3] received client metadata from 127.0.0.1:60388 conn3: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:15 cloud-j1 mongod.27019[126144]: [conn4] received client metadata from 127.0.0.1:60390 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:15 cloud-j1 mongod.27019[126144]: [conn3] received client metadata from 127.0.0.1:60388 conn3: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:20 cloud-j1 mongod.27019[126144]: [conn4] received client metadata from 127.0.0.1:60390 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:20 cloud-j1 mongod.27019[126144]: [conn3] received client metadata from 127.0.0.1:60388 conn3: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:25 cloud-j1 mongod.27019[126144]: [conn4] received client metadata from 127.0.0.1:60390 conn4: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }
Aug 27 11:52:25 cloud-j1 mongod.27019[126144]: [conn3] received client metadata from 127.0.0.1:60388 conn3: { driver: { name: "nodejs", version: "2.2.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-187-generic" }, platform: "Node.js v12.18.3, LE, mongodb-core: 2.0.11" }

**Comment by elbaby** [comment]
Hi @xet7,

I keep googling and mongod doesn't seem to have an option to turn off these messages. Seems like the "startup" message.

Maybe you're using short-lived mongod processes and this is a "normal" indication that a process is starting?
(https://stackoverflow.com/questions/45109111/var-log-mongodb-mongod-log-endless-loop-of-open-and-close-connection-from-node-j)

I didn't read your code (and probably wouldn't help too much since the last time I did some programming I did it in Perl and it wasn't such an old language) :rofl: 

Regards

**Comment by xet7** [comment]
@elbaby 

I do encourage reading Wekan code and contribute, [even a PHP programmer was able to figure it out](https://blog.wekan.team/2018/05/wekan-v1-00-released/) :smile:

But please don't send pull requests that have Perl code :rofl:

**Comment by noor-alghamdi** [comment]
> @elbaby
> 
> I do encourage reading Wekan code and contribute, [even a PHP programmer was able to figure it out](https://blog.wekan.team/2018/05/wekan-v1-00-released/) 😄
> 
> But please don't send pull requests that have Perl code 🤣

even python programmer was able to figure it out 😄😄 I'm kidding still struggling with that and I'd really appreciate if you'll have online workshop to explain the standards on how to contribute

**Comment by xet7** [comment]
@namacoconut 

About developing:

For example, here is how to build Wekan, make some changes, and create pull request:
https://github.com/wekan/wekan/wiki/Emoji

Wekan Directory Structure:
https://github.com/wekan/wekan/wiki/Directory-Structure

Some development info:
https://blog.wekan.team/2019/04/howto-code-part-1-learning-to-learn/

What would you like to contribute? I can give info where related files are.
