### ISSUE TITLE
Card links are broken on main page 

### ISSUE THREAD

**Issue by orcu** [wekan/wekan-snap#114]
Hello,
The links of cards under a list in a board's main page are broken as they do not include the port settings. Portless card links redirect to "url not found" error page of the server. This is as opposed to other links in a board's main page such as in 'add card', 'add list', 'list settings' links as they include the port and work as intended.

Picture below is related. 

![Screenshot from 2019-11-22 19-19-34](https://user-images.githubusercontent.com/682054/69442823-4c839480-0d5e-11ea-8aed-d25200ee0e18.png)

**Comment by xet7** [comment]
## For port 80
http://localhost
```
sudo snap set wekan root-url='http://localhost'
sudo snap set wekan port='80'
```
## For port 5000
http://localhost:5000
```
sudo snap set wekan root-url='http://localhost:5000'
sudo snap set wekan port='5000'
```
## Not recommended, port 5000 sub-url
http://localhost:5000/wekan
```
sudo snap set wekan root-url='http://localhost:5000/wekan'
sudo snap set wekan port='5000'
```
## More info
https://github.com/wekan/wekan/wiki/Settings
