### ISSUE TITLE
502 Bad Gateway weka.mongodb Failed to start Service for snap application wekan.mongodb.

### ISSUE THREAD

**Issue by edgarvenom** [wekan/wekan-snap#117]
A few days ago we installed Wekan and it worked great but after the update on Monday, January 6, it stopped working.
I have tried to lift it and recover my board but it was not possible for me, the MONGODB service does not work
I can't take the backup either because the dumo doesn't work, I get the following error / var / lib / snapd / snap / wekan / 714 / bin / mongodump: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

I tried to do everything that your documentation says but I can't recover my board, or do the backup correctly

========snap version
snap    2.42.2-1.el7
snapd   2.42.2-1.el7
series  16
centos  7
kernel  3.10.0-693.17.1.el7.x86_64

==============snap services
Service        Startup   Current   Notes
wekan.caddy    disabled  inactive  -
wekan.mongodb  enabled   inactive  -
wekan.wekan    enabled   active    -

======PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
25/tcp   open  smtp
80/tcp   open  http
443/tcp  open  https
3306/tcp open  mysql
9001/tcp open  tor-orort

**Comment by xet7** [comment]
Are you using edge snap? Please change to stable:
```
sudo snap refresh wekan --stable --amend
```

**Comment by xet7** [comment]
Also, there still are problems with Snap on CentOS 7 and RHEL7:
https://github.com/wekan/wekan-snap/issues/103#issuecomment-572718481

**Comment by xet7** [comment]
Anyway, save settings to file:
```
sudo snap get wekan > snap-settings.txt
```
Then stop wekan:
```
sudo snap stop wekan
```
And backup database etc files, for example:
```
sudo su
yum install zip unzip
cd /var/snap/wekan
zip -r common.zip common
```
Then on other server, that is newest Ubuntu or Debian install Wekan Snap, stop Wekan:
```
sudo su
snap stop wekan
cd /var/snap/wekan
rm -rf common
unzip common.zip
```

**Comment by xet7** [comment]
And then add those snap settings:
```
sudo snap set wekan root-url='https://boards.example.com'
```
etc, and then start wekan
```
sudo snap start wekan
```

**Comment by edgarvenom** [comment]
hi,
good day, perform the indicated steps of migrating my board to another server, on this server we also have 7 centers and we occupy nginx, the services have been stable, but I can not visualize my site in linia I get the following error
404 Page Not Found

**Comment by edgarvenom** [comment]
How do I reinstall wekan?

**Comment by edgarvenom** [comment]
Install centos 7 (b) with nginx on a new server, as wekan previously told you and follow the instructions to copy the common folder of the production server that we will call server A to server B (which is the new one), in this server installation B had already enabled a new url cr-bck.domain.com, on server B run set wekan root-url = 'https: //original.domain.com' but it responded 404, then reactivate the url cr-bck. domain.com that refers to the backup of the production url that I had enabled on server A and I was able to reset my Board, that is, I was able to access with the users that I had and see my tasks, but when selecting a task or comments the domino cr-bck.dominio.com continues to request or continue resolving the domain 'https://original.dominio.com'.

How can I change or have my board redirected to the new domain?
How can I re-install wekan, on my server A? , this in order to re-replicate the solution they gave me on my original server

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='https://original.dominio.com'
```
Etc, see Snap install page:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by edgarvenom** [comment]
I could already reset my dashboard, apply on the source server

sudo su
yum install zip unzip
cd / var / snap / wekan
zip -r common.zip common

Move my backup to another side

and run

snap stop wekan
remove all snapd
Yum clean all

And repaint wekan from the beginning

So I did not lose my information and it was restored in the same domain and server

**Comment by pantherra** [comment]
> sudo su
> snap stop wekan
> cd /var/snap/wekan
> rm -rf common
> unzip common.zip

Hello! Its doesnt work.. I had done fresh install on debian 10, without anything. Installed wekan from scratch (snapd packet). Copied old "common" folder with, but it keep crashing after start. 5-10 second and service wekan stoped. Where is snapd wekan place logs?

**Comment by xet7** [comment]
@pantherra 

Did you reboot your debian 10 server after installing snapd ?
```
sudo snap logs wekan.wekan
sudo snap logs wekan.mongodb
```

**Comment by pantherra** [comment]
> 
> 
> @pantherra
> 
> Did you reboot your debian 10 server after installing snapd ?
> 
> ```
> sudo snap logs wekan.wekan
> sudo snap logs wekan.mongodb
> ```
no i didnt. I had a backup, before snap was updated. I rolled back vm with wekan and disabled updates with this commands.
snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
snap set system proxy.https="http://<proxy_addr>:<proxy_port>"
I think the problem is incompability between Centos 7 default kernel (3.1.*) and new snap packet.

**Comment by xet7** [comment]
Yes, there is problems with Snap on CentOS 7 https://github.com/wekan/wekan-snap/issues/103#issuecomment-571223099

On Snap, MongoDB database raw files are at `/var/snap/wekan/common/`. It's possible to:
1. Copy those raw database files to Ubuntu server that has MongoDB 3.x (for example 3.2.22) installed
2. Stop MongoDB `sudo systemctl stop mongod`
3. Copy raw database files to `/var/lib/mongodb` with same file permissions with chown/chmod as original `/var/lib/mongodb` directory
4. Do `mongodump` like mentioned at [Backup page](https://github.com/wekan/wekan/wiki/Backup)
5. Restore that dump directory to Snap that is running on newest Ubuntu or Debian with:
```
sudo snap stop wekan.wekan
sudo snap start wekan.mongodb
mongorestore --drop --port 27019
sudo snap start wekan.wekan
```
Some parts of that process is also described here:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by edgarvenom** [comment]
@pantherra 

Back up the common folder well and move it from location, then completely unpack it wekan and snapd, clean your cache.
Then install again as the wekan guide says, and check that your services are running correctly.
then stop all your services and delete the common folder and then unzip your backup.
start your services as indicated in the documentation
