### ISSUE TITLE
install let's encrypt in snaps wekan?

### ISSUE THREAD

**Issue by Michael2222** [wekan/wekan-snap#118]
Hello,

I have installed wekan with the ubuntu 18.04 server installation with snaps.

Now I want to install a SSL let's encrypt certificate.

I have found an issues, but this is 4 years old:
https://github.com/wekan/wekan/issues/691

Is there a new easy way to install let's encrypt in snaps wekan?

Thanks
   Michael

**Comment by xet7** [comment]
https://github.com/wekan/wekan-snap/wiki/Install#optional-install-caddy---every-site-on-https

**Comment by Michael2222** [comment]
> 
> 
> https://github.com/wekan/wekan-snap/wiki/Install#optional-install-caddy---every-site-on-https

I have look at this link:

> 7) Add domain to Caddy config
> nano /var/snap/wekan/common/Caddyfile

I have download the official ubuntu 18.04 server iso file and have installed wekan as part of the ubuntu installation.

Then I have show in the /var/snap folder, but there is no folder wekan, there is only a folder "core" and in this the folder are
drwxr-xr-x 2 root root 4096 Jul 18  2019 8213
drwxr-xr-x 2 root root 4096 Jul 18  2019 8268
drwxr-xr-x 2 root root 4096 Jul 18  2019 common
lrwxrwxrwx 1 root root    4 Dez 12 15:10 current -> 8268

Who is the file wekan/common/Caddyfile?
Thanks
   Michael

**Comment by xet7** [comment]
Yes, you have common directory there. Under it, have Caddyfile.

**Comment by Michael2222** [comment]
OK, now I have edit the Caddyfile to:
```
http://:8080
proxy / localhost:3001 {
  websocket
  transparent
}

## SSL/TLS example. Firefox Inspect Console does not support http/2, so turning it off
## so that Firefox would not show wss websocket errors. Chrome console supports http/2.
#
test.dyndns.org {
  tls {
    alpn http/1.1
  }
   proxy / localhost:3001 {
     websocket
     transparent
  }
}
```
Wekan run in a virtual machine after my router. I have a dyndns and the standard 443 port is in use, so I must get another port for SSL to forewarding to wekan SSL.
If I now input test.dyndns.org:3001 the browser write:
`An error occurred during a connection to test.dyndns.org:3001. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG`
What do I wrong?
Thank you!

**Comment by xet7** [comment]
You should remove this:
```
http://:8080
proxy / localhost:3001 {
  websocket
  transparent
}
```
And then:
```
sudo snap set wekan caddy-enabled='true'
```

**Comment by Michael2222** [comment]
Hello,

first I will try SSL in my local network (192.168.178.94), so I have change the Caddyfile to:

```
192.168.178.94 {
  tls {
    alpn http/1.1
  }
   proxy / localhost:3001 {
     websocket
     transparent
  }
}
```
then
`sudo snap set wekan caddy-enabled='true'`
and then input in my browser 
`192.168.178.94:3001`
wekan is showing, but not secure:
![grafik](https://user-images.githubusercontent.com/7198272/73593318-0fc4de00-4503-11ea-935a-ce297a55d2f9.png)

What can I do?
Regards
   Michael

**Comment by xet7** [comment]
@Michael2222 

I think it's not possible to get SSL for local network IP addresses. See https://github.com/wekan/wekan/issues/2896#issuecomment-577257140

**Comment by ksaadDE** [comment]
> @Michael2222
> 
> I think it's not possible to get SSL for local network IP addresses. See [wekan/wekan#2896 (comment)](https://github.com/wekan/wekan/issues/2896#issuecomment-577257140)

I need to politely disagree with this. Please look at my little writeup regarding this.
