### ISSUE TITLE
Wekan doesn't work after six months

### ISSUE THREAD

**Issue by stfnnnhfn** [wekan/wekan-snap#119]
Ubuntu 16.04
Wekan doesn't work anymore. Without any changes it works fine for the last six months. 

I've had some trouble with the ssh-service as well. It fails after rebooting because directory /var/run/sshd was missing. 
I could solve this by creating this directory and restarting ssh with
systemctl restart ssh

I checked failed services with 
systemctl | grep failed and found the following:  
● snap.wekan.caddy.service                                                                                                                                           loaded failed failed    Service for snap application wekan.caddy
● snap.wekan.mongodb.service                                                                                                                                         loaded failed failed    Service for snap application wekan.mongodb
● snap.wekan.wekan.service                                                                                                                                           loaded failed failed    Service for snap application wekan.wekan
● snapd.seeded.service                                                                                                                                               loaded failed failed    Wait until snapd is fully seeded
● snapd.service                                                                                                                                                      loaded failed failed    Snappy daemon
● snmpd.service                                                                                                                                                      loaded failed failed    LSB: SNMP agents
● systemd-tmpfiles-setup.service                                                                                                                                     loaded failed failed    Create Volatile Files and Directories
● snapd.socket                                                                                                                                                       loaded failed failed    Socket activation for snappy daemon

Can you please help here ?
Best regards, 
Stefan

**Comment by stfnnnhfn** [comment]
Now I found the reason why ssh didn't work. There was a change of the owner of directory /var
so that root couldn't create the directory /var/run/sshd.
So I did now:
chown root /var
and rebooted for test. And it works fine. 
Is it possible that directory ownership could be the reason for wekan too ?
Stefan

**Comment by xet7** [comment]
Yes, Wekan files are at /var/snap/wekan . If owner of directory is not correct, Wekan does not work.

**Comment by stfnnnhfn** [comment]
Hello Lauri, 

obviously there are files and directories set to 777 and root:root. 
can you advise how they should be set. 
How can I start wekan again ?
Thanks and best regards, 
Stefan

**Comment by xet7** [comment]
```
sudo snap start wekan
```

**Comment by stfnnnhfn** [comment]
error: cannot communicate with server: Post http://localhost/v2/apps: dial unix /run/snapd.socket: connect: connection refused

**Comment by xet7** [comment]
@stfnnnhfn 

What permissions you have at `/run/snapd.socket` ?
```
ls -lah /run/snapd.socket
```
Usually snapd is installed this way:
```
sudo apt-get install snapd
reboot
```

**Comment by xet7** [comment]
You could start snapd:
 ```
sudo systemctl start snapd
sudo systemctl enable snapd
```

**Comment by stfnnnhfn** [comment]
sudo systemctl start snapd
Job for snapd.service failed because the control process exited with error code. See "systemctl status snapd.service" and "journalctl -xe" for details.


sudo ls -lah /run/snapd.socket
srw-rw-rw- 1 root root 0 Feb  4 16:02 /run/snapd.socket

**Comment by xet7** [comment]
Try:
```
sudo snap stop wekan
sudo snap get wekan > /home/snap-get-wekan.txt
sudo mv /var/snap/wekan/common /home/
sudo snap remove wekan
sudo apt-get --purge remove snapd
sudo apt-get install snapd
sudo snap install wekan
sudo snap stop wekan
sudo rm -rf /var/snap/wekan/common
sudo mv /home/common /var/snap/wekan/
sudo reboot
```
After that, look what settings you had at `/home/snap-get-wekan.txt` and add them again, for example:
```
sudo snap set wekan root-url='http://localhost'
```

**Comment by stfnnnhfn** [comment]
I cannot stop wekan due to error message
error: cannot communicate with server: Post http://localhost/v2/apps: dial unix /run/snapd.socket: connect: connection refused

and i cannot retrieve the settings because of the same message
should I continue with mv ... ?

**Comment by stfnnnhfn** [comment]
As I understand this will re-install wekan.
I have a backup of latest running version (mongodump)

**Comment by stfnnnhfn** [comment]
does it also re-install mongodb ?

**Comment by xet7** [comment]
@stfnnnhfn 

Yes, you should continue with mv etc. This will reinstall Wekan.

**Comment by xet7** [comment]
Wekan snap includes mongodb.

**Comment by stfnnnhfn** [comment]
Because I couldn't save the settings I constructed them from my old documents and it look like:

sudo snap get wekan
Key            Value
caddy-enabled  false
port           8080
root-url       http://192.168.114.205

But I cannot start wekan using http://192.168.114.205:8080

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='http://192.168.114.205:8080'
```

**Comment by xet7** [comment]
```
sudo snap set wekan port='8080'
```

**Comment by stfnnnhfn** [comment]
no difference . does not start

**Comment by stfnnnhfn** [comment]
hold on - I think i have it now 
Just checking

**Comment by stfnnnhfn** [comment]
Yep - seems to run properly. 
Thanks a lot Lauri. 
You've made my day
regards, Stefan
