### ISSUE TITLE
Feature Request: add caddy support 

### ISSUE THREAD

**Issue by scoopex** [wekan/wekan-snap#12]
Compareable with Rocket Chat it would be nice to have automatic ssl termination in the Wekan snap package.

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl

**Comment by kubiko** [comment]
yeah, this should be simple…… once I have some time to look into it :)

**Comment by kubiko** [comment]
Sorry this took long, I now prepared test build with caddy included, it's disabled by default, but you can simply enable it by calling:
$ snap set wekan caddy-enabled=true
and restart wekan ( $ snap disable wekan; snap enable wekan)
Restar won't be soon needed as I'm waiting for feature to land in snapd and then we can start/stop/restart services from configure hook when user changes settings
Test build is here:
https://launchpad.net/~ondrak/+snap/wekan-ondra-devel/+build/102386
Install like this:
$ snap install wekan_0.54-9-ga2e56c2_amd64.snap —dangerous

**Comment by xet7** [comment]
@kubiko 

Please add settings keys to wiki:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

etc where needed at Wiki pages.

**Comment by kubiko** [comment]
I have also updated wiki to reflect new changes

**Comment by xet7** [comment]
@kubiko 

I did make new snap-only release with your changes, there's info about it at:
https://github.com/wekan/wekan/releases/tag/v0.76
