### ISSUE TITLE
Wekan board page does not show

### ISSUE THREAD

**Issue by CCmesch** [wekan/wekan-snap#120]
Hi there

Since the update on the latest wekan version (3.8.3) vivaldi and firefox browsers on my opensuse machine (15.1, X86_64) don't show the wekan page any more http://[myhomeserverIP]:8080/wekan
Before it used to work. You can see the page in analysis mode: on the left you see only a grey area where the board page should be displayed. On the right I have opened the inspector area of the browser where it displays error messages, which don't tell me anything.
Using a few tricks I can load the page, though:
When I then replace the http://[myhomeserverIP]:8080/wekan  with 
http://[myhomeserverIP]:8080/wekan/sign-in/, and additionally play around in the inspector area with the links, it will suddenly display.
But the error is the same when I load the sign-in page http://[myhomeserverIP]:8080/wekan/sign-in/ right away, so that is not the problem.
The problem occors EVERYTIME I open the page in my browser window.
When I have reached the stage of displaying the page, it works just as normal
![wekan-errorpage](https://user-images.githubusercontent.com/47115232/76681817-3ba1ac00-65f7-11ea-9760-754d61a6d523.png)

Thanks for helping

**Comment by xet7** [comment]
Try this:
```
sudo snap set wekan root-url='http://[myhomeserverIP]:8080'
sudo snap set wekan port='8080'
```
Then browse to http://[myhomeserverIP]:8080/sign-in

**Comment by xet7** [comment]
If images do not then show properly, try this instead:
```
sudo snap set wekan root-url='http://[myhomeserverIP]:8080/wekan'
sudo snap set wekan port='8080'
```
Then browse to http://[myhomeserverIP]:8080/wekan/sign-in

**Comment by CCmesch** [comment]
Thanks a lot for replying so quickly!!
But sadly, this doesn't solve the issue. The page had been configured earlier and was working before.
I have opened my server and called the given commands. I tried both. Sorry!
Have you got another idea?

**Comment by xet7** [comment]
@CCmesch 

What OS and OS version your server has?

I'll try to install OpenSuse to see this error.

For me, my installed Wekan Snap v3.83 still works on my Debian server, so I need to check is this about some browser version or some other issue.

**Comment by CCmesch** [comment]
Ok:
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
kernel: 4.12.14-lp151.28.36-default  (x64)

WAIT: on firefox it now works!!!

But vivaldi browser is my standard browser: 
Vivaldi | 2.1.1337.51 (Stable channel) (64-Bit)
Vivaldi is made possible by the Chromium open source project 

can You find the problem nevetheless?

Thanks for helping

**Comment by CCmesch** [comment]
Don't the error messages at the bottom right corner of the screenshot tell you anything? 
I've copied them here:
Uncaught ReferenceError: meteorBabelHelpers is not defined
    at 4695928a00eb48e08bfa75eaa85b1eadb6c75240.js?meteor_js_resource=true:222
    at 4695928a00eb48e08bfa75eaa85b1eadb6c75240.js?meteor_js_resource=true:222
    at 4695928a00eb48e08bfa75eaa85b1eadb6c75240.js?meteor_js_resource=true:222
4695928a00eb48e08bfa75eaa85b1eadb6c75240.js?meteor_js_resource=true:190 
There is no route for the path: /

**Comment by CCmesch** [comment]
On firefox it now works, but still not with vivaldi browser (which is standard on my machine)

**Comment by xet7** [comment]
Well, many websites do not work in vivaldi. I'm not able to fix any vivaldi bugs, it's their webbrowser.

**Comment by CCmesch** [comment]
Hmmm. Sad. They use the chromium web engine, though. Could it be a problem connected with chromium browser?

**Comment by CCmesch** [comment]
damn. It used to work until recently.

**Comment by xet7** [comment]
Wekan works in Chromium-based browsers, but Vivaldi does add it's own bugs so then Wekan does not work on Vivaldi.
