### ISSUE TITLE
Error 502  UTC Bad gateway

### ISSUE THREAD

**Issue by edgarvenom** [wekan/wekan-snap#123]
Good day
When entering my board we detect that it is not working correctly
It is mounted on a 7 cent, and it always happens to me that every 3 months or 2 Mongo stops working and I have to back up my app and reinstall everything from scratch to later mount my backup.
Is there an easier way to fix this.

[root@prdbambu01 ~]# systemctl status  snap.wekan.wekan
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-05-18 10:16:57 CDT; 2s ago
 Main PID: 7561 (wekan-control)
   CGroup: /system.slice/snap.wekan.wekan.service
           ├─7561 /bin/bash /snap/wekan/839/bin/wekan-control
           └─8922 /snap/wekan/839/bin/node main.js

May 18 10:16:57 prdbambu01.cloud systemd[1]: Started Service for snap application wekan.wekan.
You have mail in /var/spool/mail/root

[root@prdbambu01 ~]# systemctl status snap.wekan.mongodb
● snap.wekan.mongodb.service - Service for snap application wekan.mongodb
   Loaded: loaded (/etc/systemd/system/snap.wekan.mongodb.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2020-05-18 10:16:59 CDT; 1min 10s ago
  Process: 7494 ExecStart=/usr/bin/snap run wekan.mongodb (code=exited, status=2)
 Main PID: 7494 (code=exited, status=2)

**Comment by xet7** [comment]
Is it possible that you [Backup](https://github.com/wekan/wekan/wiki/Backup) and restore to Ubuntu 20.04 64bit server? Because this has never happened me on Ubuntu server.
