### ISSUE TITLE
Acesss has been blocked by CORS policy when using API outside of it's host

### ISSUE THREAD

**Issue by erezsdev** [wekan/wekan-snap#125]
I am using Angular application that should make requests for the WeKan API, however, the API decline the requests because of CORS policy:

`Access to XMLHttpRequest at 'http://someip:3001/users/login' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`

Tried to `sudo snap set wekan cors='*'` but nothing happens, even after a restart.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/snap-src/bin/config#L129-L139
