### ISSUE TITLE
Export board not working

### ISSUE THREAD

**Issue by gusarg81** [wekan/wekan-snap#126]
Hi,

Currently using fresh install (snap in Ubuntu 18.04) of Wekan. I've tried the export function (JSON) and it export an empty file (Ex. wekan-export-board-FSjDW8muNzHWEM5Mr.json with 0 bytes in it). The other export methods does nothing either.

Any ideas?

Thanks.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/3173#issuecomment-662003592
