### ISSUE TITLE
Open insecure connection on server

### ISSUE THREAD

**Issue by L25inux** [wekan/wekan-snap#128]
Hello I have this problem. I have installed snap Wekan on Ubuntu 20.04 LTS. Everything works smoothly. I enabled SSL via Apache but I have still insecure connection via my ip address and port. Is possible to close it or redirect to HTTPS?
I used this manual for snap install: https://github.com/wekan/wekan-snap/wiki/Install
I used this manual for Apache+SSL install: https://github.com/wekan/wekan/wiki/Apache

So for example https//wekan.example.com it works http forwards to HTTPS variant of my address. 
http://ip_address also forwards to HTTPS variant. If I type IP_Address:3001 website is on insecure connection. Is possible close it or forward to secure HTTPS? 

Thank you very much for help. 

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/69634168/90259212-f1448580-de49-11ea-8748-c4bdbb372dc2.png">

**Comment by xet7** [comment]
It is not easy to get SSL cert for IP address. Your server is at local network, that most likely can not be accessed via Internet.

SSL is used only at Internet server, where server has public IP address. Then you buy domain like example.com from https://namecheap.com or some other domain provider, and set A record to your server public IP address. Then you can access server at `https://example.com` or similar address.

Wekan Snap install info has details how to use Caddy webserver (that is included with Wekan Snap) to get automatic SSL with Let's Encrypt. Apache and Nginx are much harder to configure.
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
Those local network IP addresses like `192.168.x.x` and `10.x.x.x` are not accessible from Internet, they are reserver for local network use.
