### ISSUE TITLE
All users deleted after latest snap update - and everyone who is signed in gets signed in as the latest person who signs in

### ISSUE THREAD

**Issue by gummozz** [wekan/wekan-snap#132]
Terribly sorry for the confusing title - but it's really what's happening.

All users are deleted from Wekan since the last update. User just noticed. I managed to go into the MongoDB and make myself admin in order to check the users - they are not in the system. Board data seems to be fine - but since the users accounts are gone no one can actually see them. It is possible to register new accounts, but the following happens:

Using OIDC.

When I sign in - I'm signed in as Firstname Lastname, and my username become "firstnamelastname", instead of the preffered_username it should be (filas@domain.com). When another user signs on, my account in the top right corner is changed to that persons account. Not only the name, I'm actually signed in as that user.

I would share logs but I can't figure out how to display more than the tail using "snap logs wekan". I'll gladly provide any info needed to help me resolve this. Pretty major bug. Pretty sure it's not our fault since I (the only admin) havn't touched the system for months...

**Comment by xet7** [comment]
@gummozz 

I don't know are you looking at correct database.

At server as root type this to use MongoDB CLI and show count of users:
```
export LD_LIBRARY_PATH=/snap/wekan/current/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export PATH=/snap/wekan/current/bin:$PATH
mongo --port 27019
use wekan
db.users.count();
```
You can also see some user data with:
```
db.users.find();
```
Then exit MongoDB cli:
```
exit
```

Then check your snap settings:
```
snap get wekan
```
For example, OIDC settings for Azure: https://github.com/wekan/wekan/wiki/Azure

**Comment by xet7** [comment]
What OIDC identity provider you use?

**Comment by xet7** [comment]
When you look at Admin Panel / People, are your users there?

At Admin Panel Settings, do you have default login method as OAuth2? So it's not set to Password method?

For users, have you edited all users and set OAuth2 as their login method?

**Comment by xet7** [comment]
Does that server have enough free disk space? Check with:
```
df -h | grep -v snap
```
Does that server have enough RAM, so it is not swapping? Check with:
```
free -h
```

**Comment by xet7** [comment]
If you like to just edit-copy-paste with nosqlbooster GUI, you could look at user ids from users collections/table, and paste them to members field of boards.

Wekan also has API, so with it you can do some stuff like this, if you like coding:

https://github.com/wekan/wekan/wiki/REST-API-User#example-call---as-form-data

With your Wekan username and Wekan URL, login to Wekan API to get Bearer token this way:

```
curl http://localhost:3000/users/register \
     -d "username=myusername&password=mypassword&email=my@email.com"
```
https://wekan.github.io/api

**Comment by xet7** [comment]
And API example using Python:
https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API

**Comment by gummozz** [comment]
Thank you for getting back so fast with so much! I'll try to answer everything here:

Regarding database - I confirmed it's the correct database by modifying a user directly in the database, and the changes shows in Wekan. I also noticed my changes that I did yesterday to that user is gone (I made my account admin).

There's still only two users in the "People" tab of wekan - however, while it was me and "mr x" yesterday - it is me and "mr y" today. Like it's "max two people fit in the db", and one is being overwritten.

```
> use wekan
switched to db wekan
> db.users.count();
2
```

Space: Does not look good on the "snap" parts:

```
/dev/loop1       97M   97M     0 100% /snap/core/9665
/dev/loop0      176M  176M     0 100% /snap/wekan/913
/dev/loop2       97M   97M     0 100% /snap/core/9804
```

There is free space on disk, though. How can I make sure snap gets the disk it needs?

Memory looks good:

```
              total        used        free      shared  buff/cache   available
Mem:           3.8G        539M        2.5G         39M        867M        3.0G
Swap:          4.0G          0B        4.0G

```
I'm using **Okta** as an identity provider.

**Comment by gummozz** [comment]
I can confirm that the boards still exist in the database - I was able to recover the most critical one by modifying the "personal" permission to "public". I was not able to do the same on the next board. The change is made in the database but does not show up on the "/public" part of Wekan. Continuing odd behaviour.

**Comment by xet7** [comment]
@gummozz 

You should add users to members of those boards, by editing board JSON and adding user ids. That would be more useful than making boards public.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/3259
