### ISSUE TITLE
can't connect nginx with wekan

### ISSUE THREAD

**Issue by noor-alghamdi** [wekan/wekan-snap#133]
@xet7 
hello everyone,

I'm trying to run wekan snap instance uing 3tiers architecture, 1layer for webe that will have nginx, the second one for App that will have wekansnap instance, and the third layer will be the DAtabase, 

on the web server I installed nginx normal installation and I added a DNS and continued the configuration as described on this link:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

but I'm not using 3001 port instead I'm using port 80!
would that cause an issue?

but now when I try to run the DNS for example : https://sometnig.com

it shows the default page of nginx, it doesn't redirect me to application!

I've worked with nginx before.

**Comment by noor-alghamdi** [comment]
@xet7 Dear mr.lauri your cooperation is really appreciated

**Comment by noor-alghamdi** [comment]
please any update!

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Settings

https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by noor-alghamdi** [comment]
Dear mr.lauri 
good morning, 

the application layer is working fine with me an I'm running the application on port 80 , but in the wb layer which has niginx installed it doesn't redirect me anywhere , it still shows nginx default page! 

this is my configuretion for App server 

![Screenshot (879)](https://user-images.githubusercontent.com/65490460/92689527-cfa2c500-f347-11ea-9147-b4db1fc4767b.png)


this is mu config for web server 
![Screenshot (878)](https://user-images.githubusercontent.com/65490460/92689543-d4677900-f347-11ea-99ac-ef8606d94f72.png)


please I need your advice

**Comment by namacoconut** [comment]
when I run the dns name in the browser it keep showing nginx default page 
this one 
![Screenshot (880)](https://user-images.githubusercontent.com/65490460/92691648-86ed0b00-f34b-11ea-9670-e05459e14cef.png)

**Comment by noor-alghamdi** [comment]
when I run the dns in browser it keeps showing nginx default page 

![Screenshot (880)](https://user-images.githubusercontent.com/65490460/92691708-aa17ba80-f34b-11ea-8ae7-a167940d272b.png)

**Comment by noor-alghamdi** [comment]
oh sorry for bothering I found that I'm saving my configuration in nginx file without ".conf" extension  :)
my bad

**Comment by xet7** [comment]
@namacoconut 

It's great you got it working! :+1: :smile:

**Comment by noor-alghamdi** [comment]
@xet7 
good morning mr.lauri,

how to access the DB data if I am using snap instance? 


thank you.

**Comment by xet7** [comment]
@namacoconut 

With nosqlbooster GUI, connect via SSH to Wekan server localhost port 27019.
