### ISSUE TITLE
nginx proxy pass show the server IP

### ISSUE THREAD

**Issue by noor-alghamdi** [wekan/wekan-snap#134]
hello mr.lauri @xet7 
I have a problem when redirecting from web to app layer,
it creates aboard with lists but when I click on some card it shows the IP address for App server + not connecting! 

![Screenshot (905)](https://user-images.githubusercontent.com/65490460/93870286-a97d0d80-fcd5-11ea-9faf-bd9bedae5ac3.png)
![Screenshot (904)](https://user-images.githubusercontent.com/65490460/93870291-aaae3a80-fcd5-11ea-8138-471a51d787f0.png)

my nginx configuration similar to the one in official documentation :

`# this section is needed to proxy web-socket connections
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# HTTP
server {
    listen 80; # if this is not a default server, remove "default_server"
    listen [::]:80 ipv6only=on;

    server_name example.com;

    # redirect non-SSL to SSL
    location / {
        rewrite     ^ https://example.com$request_uri? permanent;
    }
}

# HTTPS server
server {
    listen 443 ssl http2; # we enable HTTP/2 here (previously SPDY)
    server_name example.com; # this domain must match Common Name (CN) in the SSL certificate

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    # If your application is not compatible with IE <= 10, this will redirect visitors to a page advising a browser update
    # This works because IE 11 does not present itself as MSIE anymore
    if ($http_user_agent ~ "MSIE" ) {
        return 303 https://browser-update.org/update.html;
    }

    # Pass requests to Wekan.
    # If you have Wekan at https://example.com/wekan , change location to:
    # location /wekan {
    location / {
        # proxy_pass http://127.0.0.1:3001/wekan;
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP

        # this setting allows the browser to cache the application in a way compatible with Meteor
        # on every applicaiton update the name of CSS and JS file is different, so they can be cache infinitely (here: 30 days)
        # the root path (/) MUST NOT be cached
        #if ($uri != '/wekan') {
        #    expires 30d;
        #}
    }
}`

**Comment by xet7** [comment]
Did you set Wekan ROOT_URL for example:
```
sudo snap set wekan root-url='https://wekan.example.com'
```
https://github.com/wekan/wekan/wiki/Settings

**Comment by noor-alghamdi** [comment]
Yes , worked perfectly 👌😍

Thank you

**Comment by noor-alghamdi** [comment]
@xet7  hey mr.lauri, I chaecked the support plans , what is the deference between them?

**Comment by xet7** [comment]
@namacoconut 

Paid Commercial Support at https://wekan.team/commercial-support/ has:
- Private encrypted email support
- I can install Wekan and some integrations to your server directly
- Priority prepaid feature and fix development
- For those that have yearly support plans of 2000 euro/year, there is private chat support

These GitHub issues here at https://github.com/wekan/wekan/issues are:
- Free Public Community Support with public messages, visible to everyone at Internet
- No anyones private server info added to any of these public messages
- Answers to Global Wekan Community Contributors that send pull requests to Wekan, those are integrated to public Wekan releases. Anyone can code and send feature or fix to Wekan as pull request for free.
