### ISSUE TITLE
Do you have privacy policy?

### ISSUE THREAD

**Issue by noor-alghamdi** [wekan/wekan-snap#137]
Dear mr.Lauri,
I hope you are doing well,

I need to add the privacy policy to wekan instance I have, do you have any idea where can I add it? 

thank you.

**Comment by xet7** [comment]
@namacoconut 

It is your Wekan instance and your privacy policy, how you handle that data. You should write it yourself. I do not have any access to your Wekan instance.

For my own hosted Wekan instances, I have this privacy policy:
https://wekan.team/privacy/

But you can not use "Wekan Team" and my name in your privacy policy. Data is at your server. Not at my server. At your privacy policy, there should be your details.

**Comment by noor-alghamdi** [comment]
oh no hahahaha, 
not like that , I mean that where to add my privacy policy link? there is no such a footer in snap instance , 
@xet7 
is there something like snap set privacy_link??

**Comment by xet7** [comment]
@namacoconut 

For example: Admin Panel / Layout / Text below Login Logo.

There is not yet footer text feature.

**Comment by xet7** [comment]
Text below Login Logo is a new feature:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v441-2020-10-03-wekan-release

It can also have markdown, [Emoji](https://github.com/wekan/wekan/wiki/Emoji), etc.

**Comment by xet7** [comment]
Markdown link works like this:
```
[Privacy Policy](https://example.com/privacy/)
```

**Comment by noor-alghamdi** [comment]
> Markdown link works like this:
> 
> ```
> [Privacy Policy](https://example.com/privacy/)
> ```



I added it like this:

```
<h2><a href="https://example.com/PrivacyPolicy"> privacy policy</a>  
  and
<a href="https://example.com/usagepolicy">usage policy</a>
</h2>
```

**Comment by noor-alghamdi** [comment]
@xet7 I have a concern that the documentation is not that clear for tool installation on linux without using docker or snap!
I tried to install the tool and initiate the services I didn't work,  I followed these tutorial 
https://www.howtoforge.com/tutorial/centos-wekan-installation/

**Comment by xet7** [comment]
@namacoconut 

I recommend Snap on Ubuntu 20.04 64bit. That is what has always worked for me.

I don't recommend CentOS or RedHat. There has been some problems with Snap updates on those OSes.

**Comment by xet7** [comment]
With Snap on CentOS or RedHat after some Snap update Wekan has not started at all, it has required reinstall of Wekan, and restore from backup.

**Comment by noor-alghamdi** [comment]
> With Snap on CentOS or RedHat after some Snap update Wekan has not started at all, it has required reinstall of Wekan, and restore from backup.

I stopped automatic updates , but I'm saying that I'd love to learn how to install and deploy the tool without snap or docker but the documentation is not clear for that.

**Comment by xet7** [comment]
Bundle works without Snap and Docker, for x64/arm64/s390x, on PCs/servers/RasPi etc:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

**Comment by xet7** [comment]
@namacoconut 

Related https://github.com/wekan/wekan-snap/issues/129 , thinking how to make it easier.
