### ISSUE TITLE
Wekan Admin access

### ISSUE THREAD

**Issue by noobsaibo** [wekan/wekan-snap#14]
Hello

How could I list the users and how can I delete the old users, the installation does snap

Thank you

**Comment by xet7** [comment]
@noobsaibo 

There is not web interface for user management yet on Admin Panel.

There could be possibility to list users using API:
https://github.com/wekan/wekan/issues/1037

All Wekan data is at MongoDB database. There are some cleanup scripts at:
https://github.com/wekan/wekan-cleanup

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/802
