### ISSUE TITLE
Move card from a board to another does not work anymore

### ISSUE THREAD

**Issue by lezioul** [wekan/wekan-snap#141]
Hi,

in previous version i was able to move a card from a board to another, which is very handy to organise some task (at least, i found it handy).
There is a way to copy a card and paste it to another board and then delete the original, but in this workaround, attachments are lost.
Am i missing something?

BR,
lezioul

**Comment by xet7** [comment]
Hmm? Maybe related to https://github.com/wekan/wekan/issues/3377

**Comment by lezioul** [comment]
I am admin, and i am not able to move cards from board to another anymore.
I can test with a "simple" user with another role.
