### ISSUE TITLE
Board Model and Labels

### ISSUE THREAD

**Issue by jmblanc** [wekan/wekan-snap#143]
Labels from board model and new boards from this model disappear from the board menu, but still appear in the json export (Wekan Version 4.69.0, snap).

Let me know for more explanation, Thanks.

**Comment by xet7** [comment]
@jmblanc 

Please upgrade to newest Wekan with `sudo snap refresh`

Does it still happen in newest Wekan? Please add anonymized screenshot.

**Comment by jmblanc** [comment]
it works ! Thanks 👍
