### ISSUE TITLE
Issue to rename email?

### ISSUE THREAD

**Issue by killmasta93** [wekan/wekan-snap#144]
Hi,
I was wondering if someone could shed somelight, currently trying to rename an email but on the admin page does not let me. i tried deleting also there is no option any ideas how to?

Thank you

**Comment by xet7** [comment]
@killmasta93 

Check your Admin Panel Settings:

![Screenshot_20210113-032106_Chrome](https://user-images.githubusercontent.com/15545/104394136-a771df80-554e-11eb-82d7-801a0104247f.png)

**Comment by xet7** [comment]
Deleting feature is hidden because it's not ready yet, it leaves empty avatars to boards for deleted users, so it's not useful at all yet.

**Comment by killmasta93** [comment]
thanks for the reply, i did check the delete feature but then i realize its better to just change the email but couldn't find a way

**Comment by xet7** [comment]
@killmasta93 

After allowing email change in those settings, did changing email work?

**Comment by killmasta93** [comment]
@xet7 thanks for the reply, i added the feature but i tried changing it and it wont change very odd

![image](https://user-images.githubusercontent.com/13953629/104535503-53193f00-55e4-11eb-8e1e-84b1bfd0952f.png)

**Comment by xet7** [comment]
@killmasta93 

Thanks for info! I will try it myself, and if it does not work, I try to fix it.

**Comment by killmasta93** [comment]
thank you again

**Comment by xet7** [comment]
@killmasta93 

When I tried, renaming email is possible. Try this:

1. Update to newest Wekan. For Wekan Snap version, at shell type: `sudo snap refresh`
2. At Admin Panel / People, search for your email and username to change.
3. Click Edit on that username
4. Change email address
4. Click Save

**Comment by killmasta93** [comment]
thanks for the reply, updating did the trick
