### ISSUE TITLE
Error on enabling email support

### ISSUE THREAD

**Issue by dvolozhinok** [wekan/wekan-snap#145]
Hello, dear Wekan developers!

Work space: Centos 7, Wekan from snap and Nginx proxy with self-signed certificate.
Error when enabling email support and then trying to send test email through Wekan admin interface:

Отправка письма на EMail не удалась
Ошибка при попытке отправить письмо:
139821095712576:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

1. What logs do you need to figure out why it's happening?
2. What can cause such problem?

**Comment by xet7** [comment]
Try these settings:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#starttls-sending-test-email-failed
