### ISSUE TITLE
Backing up wekan causes permission denied error

### ISSUE THREAD

**Issue by 9a3eedi** [wekan/wekan-snap#15]
I am attempting to back up wekan-snap, so I followed the [documentation on the wiki](https://github.com/wekan/wekan-snap/wiki/Backup-and-restore). This is what I get when I try to back it up.

```
$ sudo wekan.database-backup test
using default value: MONGODB_BIND_UNIX_SOCKET='/var/snap/wekan/64/share'
using default value: MONGODB_BIND_IP=''
using default value: MONGODB_PORT='27019'
using default value: MAIL_URL='smtp://user:pass@mailserver.examples.com:25/'
using default value: MAIL_FROM='wekan-admin@example.com'
ROOT_URL='http://192.168.0.51:80/wekan'
PORT='80'
using default value: DISABLE_MONGODB='false'
using bind ip
2017-09-26T10:20:22.327+0400	Failed: open test: permission denied

```
I currently have 0.43 installed.  

Also, since this is a snap, is it supposed to go to the system /var directory? Or is there a snap specific /var directory that it uses?

**Comment by xet7** [comment]
@9a3eedi 

I updated backup documentation, please try again with those changes.

**Comment by 9a3eedi** [comment]
@xet7 it works now. Thank you very much!

**Comment by kubiko** [comment]
thank @xet7 
@9a3eedi to explain about permissions where snap package can access.
Snap's writable service data for snap's sandbox are store in
/var/snap/<snap name>/common
/var/snap/<snap name>/current
There are also then writable data per user if you invoke snap's application from user's shell, that is then under:
/<user's home>/snap/<snap name>/common
/<user's home>/snap/<snap name>/current
In case of wekan, we do not really use per user data as it runs as a service.

**Comment by ghost** [comment]
Dear i can't restore a backup, it says there are conflicts :
2018-09-26T09:40:08.022+0200    error: multiple errors in bulk operation:
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "4ZxcrsoDESWFzDAz8" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "7bkxnMKjS7md9ig5A" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "yasNJiLvHEYqEYwaK" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "LpCWiiD4oyj6tiNCw" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "RLmryYL8pLqcnkwpg" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "87kk44ji227rsNRLZ" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "2THA3N6zxZLREBr2r" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "8R3276eRKxEaYJ2nE" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "hXZWcrMssm4ydqsPe" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "hJYaWCNhYuc2arGWx" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "pa3PigQSnJwgoJx4g" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "z8ovZLZH3PRDwHyHE" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "9o378YKLh3d6vu3eS" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "G7eBg2b3XAzkRPxPB" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "oPmha2kbANPTALBHG" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "E4PMa59fJgobppzvd" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "Zf8vutK5ANeWQ2pp5" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "KZ38SJqfkaAytbRs4" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "z84YzTySLturvcjgH" }
  - E11000 duplicate key error collection: wekan.meteor-migrations index: _id_ dup key: { : "KKtQer2zApiHtDknD" }

**Comment by ghost** [comment]
i tried to reinstall but now i can't backup i get this : Backing up users and roles is only supported for clusters with auth schema versions 1 or 3, found: 5
