### ISSUE TITLE
How can I setup the cron for email reminder job?

### ISSUE THREAD

**Issue by mdemori** [wekan/wekan-snap#152]
Hi, 

I've installed wekan Snap version and configured everything for e-mail delivery with smtp, sending the test message through the UI work as expected. 

Now I don't understand how can I set-up a cron job that check if there are some reminder to send.. there is something that the Snap version do by itself? Sorry but I can't find any documentation on this topic and I don't know snap very well :(

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2026#issuecomment-1013335715
