### ISSUE TITLE
Is the snap version still updated? 

### ISSUE THREAD

**Issue by mdemori** [wekan/wekan-snap#153]
I see that this version seem not updated for some months.. i just see that the wekan/wekan is at 5.78 version but all this change is not reflected on snap version.
If this project is no more maintained, how can i update it by myself? 

thank you!

**Comment by xet7** [comment]
@mdemori 

Snap version is still maintaned, has been for many years. Newest snapcraft.yaml etc files are now at https://github.com/wekan/wekan , not here.

WeKan version number and links to installing Snap version are at https://wekan.github.io Download / Snap Automatic Updates.

You see your Snap version with:
```
sudo snap list
```
Snap updates happen automatically. If you would like to immediately upgrade, type:
```
sudo snap refresh
```
Documentation is up-to-date currently at 2 places:
- https://github.com/wekan/wekan-snap/wiki
- https://github.com/wekan/wekan/wiki

There is also 2nd different WeKan Snap version that also has Gantt feature:
https://github.com/wekan/wekan/wiki/Gantt
