### ISSUE TITLE
Unable to change cards after update

### ISSUE THREAD

**Issue by wrrdlbrrmpft** [wekan/wekan-snap#154]
I cannot save changed contents of cards since one of the last updates. I can click the card end edit the text (within main text field or within comment fields). But these changes disappear after saving.

Our installation is debian buster.

First question, where can I find some debug information?

**Comment by xet7** [comment]
@wrrdlbrrmpft 

Please update to newest snap with:
```
sudo snap refresh
```
Then please copy output of this command to comment of this issue:
```
sudo snap list
```
And test does it still happen.

**Comment by wrrdlbrrmpft** [comment]
@xet7: Wow,what a quick answer. Thank you.

Here's the output:
`
Name   Version    Rev    Tracking       Publisher   Notes
`
`
core   16-2.52.1  11993  latest/stable  canonical✓  core
`
`
wekan  5.84       1855   latest/stable  xet7        -
`
Unfortunately, it's not solved. Do I need to restart anything?

**Comment by xet7** [comment]
@wrrdlbrrmpft 

Please clean up your browser cache, close browser, open browser, login to WeKan, and try again.

What browser and browser version you use?

**Comment by xet7** [comment]
Does this happen on newest Firefox or Chromium?

**Comment by wrrdlbrrmpft** [comment]
No, it doesn't. Finally, I updated my browser: Chromium 79 -> Chromium 99. Problem solved. Thank you very much.
