### ISSUE TITLE
snap "wekan" has no updates available - worked fine until recently, I'm up to v6.09.0

### ISSUE THREAD

**Issue by tromlet** [wekan/wekan-snap#158]
Hi -

I was updating our local instance of WeKan (or, rather, trying to), and it's giving me the error message:

```shell
# sudo snap refresh wekan
snap "wekan" has no updates available
```
Even after a reboot and everything, it gives me this - and I'm currently on version 6.09.0, where the GitHub repo seems to show WeKan has been updated all the way up to 6.28. 

**Admin Panel > Version:**
It should be noted that while I *AM* using "Linux x64", I am specifically using Alma Linux 8.6 x64. Runs lickety split, except for the updating thing not working.

| Software | Detail |
|---|---|
| **Wekan Version** | 6.09.0 |
| **Meteor version** | 2.2 |
| **Node version** | 12.22.10 |
| **MongoDB version** | 3.2.22 |
| **MongoDB storage engine** | wiredTiger |
| **MongoDB Oplog enabled** |
| **OS Type** | Linux |
| **OS Platform** | linux |
| **OS Arch** | x64  |
| **OS Release** | 4.18.0-372.13.1.el8_6.x86_64 |
| **OS Uptime** | 20 hours, 52 minutes, 1 seconds |
| **OS Load Average** | 0.72, 0.15, 0.05 |
| **OS Total Memory** | 4  GB |
| **OS Free Memory** | 2  GB |
| **OS CPU Count** | 2 |

**Comment by xet7** [comment]
Please wait that I have coded mongodb version upgrades etc to Snap, and made more tests that upgrades works.

**Comment by tromlet** [comment]
Definitely cool, but does this mean updates are just... temporarily down? Will all WeKan instances not work for updating for the time being (we have another WeKan instance I was hoping to update tonight that is not regularly connected to the internet - it's currently at version 6.05?)

**Comment by xet7** [comment]
@tromlet 

Snaps that are connected to Internet will automatically update when I have released new WeKan Snap sometime in near future.

If some Snap is not reqularly connected to Internet, it will update when connected to Internet.

Manual immediate update can be made with:

sudo snap refresh

**Comment by tromlet** [comment]
That's precisely the command I have run, only to get the error message: `snap "wekan" has no updates available`

Is version 6.09.0 the most recent version of WeKan for snaps? Because that's what mine is right now, despite the WeKan GitHub repo saying you're all the way up to 6.28. :(

**Comment by xet7** [comment]
@tromlet 

There is test version, but it's not tested well yet https://github.com/wekan/wekan/issues/4505#issuecomment-1166682244

I really recommend to wait for official tested version.

**Comment by tromlet** [comment]
Oh - I will absolutely do so. I updated our air-gapped WeKan to the latest, and it got me 6.09.0. That'll do for now. If needbe, I'll update as soon as we get word that it's up-to-date!

**Comment by xet7** [comment]
@tromlet 

You see WeKan version at:
https://wekan.github.io

Changelog at:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

WeKan Snap Stable channel version at:
https://snapcraft.io/wekan

WeKan Gantt GPL Snap Stable channel version at:
https://snapcraft.io/wekan-gantt-gpl

WeKan Snaps install info at:
https://github.com/wekan/wekan-snap/wiki/Install
