### ISSUE TITLE
Backup/restore and export to another server using snapshots of snaps

### ISSUE THREAD

**Issue by lego992** [wekan/wekan-snap#159]
I checked this way to backup/restore and to export to another server with same snap installation.
Snapshots of snaps https://snapcraft.io/docs/snapshots
Tested migration from server Ubuntu 16.04 to server Ubuntu 22.04 and vice versa.

---Backup/restore on same server---

**snap save
sudo snap restore xx**    

_-xx is set number of snapshots                                      
-snapshots are stored in the /var/lib/snapd/snapshots_

---Export to another server---

**snap save
sudo snap export-snapshot xx my-snapshot1**  

_-my-snapshot1 appears in root directory
-after that we upload this file to another server and put it in the root directory(or different, then to point path)_

**sudo snap import-snapshot my-snapshot1
sudo snap restore xx
reboot**

**Comment by xet7** [comment]
Please use mongodump/mongorestore instead https://github.com/wekan/wekan/wiki/Backup
