### ISSUE TITLE
wekan snap not upgrading on Ubuntu

### ISSUE THREAD

**Issue by ktzee** [wekan/wekan-snap#161]
It looks like my snap is stuck at 6.09.0. When I try to run a refresh, it doesn't recognize any update. 

`sudo snap refresh wekan
snap "wekan" has no updates available`

sudo snap list
Name     Version    Rev    Tracking       Publisher     Notes
wekan    6.09       1998   latest/stable  xet7          -

I checked the docs/wiki, but I couldn't find anything that would seem to address this. I admit they're a bit confusing and noodly though, so I got lost several times in trying to follow the docs.

**Comment by ischeriad** [comment]
I'm also waiting for snap to catch up.
Is snap deprecated?

Or is it save to force it to another channel?

**Comment by xet7** [comment]
@ischeriad 

Newest WeKan Snap will be released after I get upgrading fixed, sometime this year I presume.

**Comment by KnudH** [comment]
I'm still on 6.09. Should I switch to docker or will you get this done? Can we support you in resolving this problem?

**Comment by xet7** [comment]
@KnudH 

Best help would be helping to figure out required changes https://github.com/wekan/wekan/issues/4780#issuecomment-1643699532

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/5475
