### ISSUE TITLE
Cors - header field authentication is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by dtrox** [wekan/wekan-snap#166]
Hey, 

I'm trying to access the wekan api via a subdomain but whenever I send a post request I get the following error `"has been blocked by CORS policy: Request header field authentication is not allowed by Access-Control-Allow-Headers in preflight response".
`
I already tried to solve the problem with `sudo snap set wekan cors-allow-origin='*' `but unfortunately without success.

I think I need to enable the "options" method to solve the problem, but I didn't find anything here "https://github.com/wekan/wekan/blob/master/snap-src/bin/config". 

Shouldn't there be something like `cors-allow-methods`?

Older threads have not helped me unfortunately. 

What am I doing wrong?

**Comment by xet7** [comment]
@dtrox 

Maybe something related is here:
- https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help#L199
- https://github.com/wekan/wekan/blob/master/server/cors.js

Maybe with this command, where snap is installed:
```
wekan.help | less
```
