### ISSUE TITLE
Option to disable login requirement

### ISSUE THREAD

**Issue by lofidevops** [wekan/wekan-snap#17]
**User story:** I am the sole user of my machine, running a local instance of `wekan-snap`. I want to open Wekan without logging in, to save time and avoid having to remember another password.

**Suggested solution:**

A configuration flag that disables the login page, and automatically logs the user in as user "wekan".

**Comment by xet7** [comment]
Use password manager in webbrowser like Firefox or Chrome to autofill your login information.
