### ISSUE TITLE
Snap stable channel release quite old with CVE

### ISSUE THREAD

**Issue by wiking-at** [wekan/wekan-snap#170]
The latest/stable channel version of the snap is already quite old (6.09 from Feb 28, 2022). 
The current version of Wekan is 7.45.

As per https://www.cvedetails.com/vulnerability-list/vendor_id-18653/product_id-47342/Wekan-Project-Wekan.html it seems that there are two security vulnerabilites unfixed in the stable channel release (Score 5.4).

I tried to manually switch to the latest/canditate channel - but the version in this channel seams to be broken.

Is it possible for the maintainers of this snap to bump the version of the latest/stable snap to a current  working version without security vulns?

Thanks!

**Comment by xet7** [comment]
@wiking-at

There will be automatic upgrade from 6.09 to newest 7.x, when I have fixed database upgrades and migrations working well enough. You are not the only one waiting for upgrade.

**Comment by paul1278** [comment]
@xet7 do you know when the update will be available?

**Comment by xet7** [comment]
@paul1278 

This issue moved to https://github.com/wekan/wekan/issues/5475#issuecomment-2271611017 where I have replied.
