### ISSUE TITLE
Connect to Wekan Snap Mongo-db

### ISSUE THREAD

**Issue by jdalmeida** [wekan/wekan-snap#171]
Hello!

I'm building a BI dashboard with data from Wekan, and I was wondering if there is a way to connect to the wekan snap mongodb database.

**Comment by xet7** [comment]
Yes, there is MongoDB at port 27019. You can connect to it with any programming language where is drivers for MongoDB 6:

https://www.mongodb.com/docs/drivers/

Other way is to connect with MongoDB GUI like Nosqlbooster or DBGate.
