### ISSUE TITLE
wekan snap 6.09.0 does not update since 2022

### ISSUE THREAD

**Issue by docknack** [wekan/wekan-snap#172]
I noticed, that my wekan is not updating since long time (2022) what is the proble? Im using the snap version. I dont want to loose my boards. What is todo? Im running on ubuntu 20.04. Thanks for help.

![Screenshot 2024-08-07 095629](https://github.com/user-attachments/assets/5cfef344-fed5-45ae-8313-36049de16023)

**Comment by xet7** [comment]
@docknack 

Yes, there will be automatic upgrade, that will be tested well, that you would not loose your boards.

More info at https://github.com/wekan/wekan/issues/5475#issuecomment-2271611017

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/5562
