### ISSUE TITLE
Publishing Wekan v0.24 snap?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#2]
@kubiko

I added changes for Wekan v0.24, MongoDB v3.2.14, wekan-ondra to wekan.

How do I build and publish it as snap package?

**Comment by xet7** [comment]
Snap is now published.

**Comment by kubiko** [comment]
I can see process is working fine for you now. I'm just finishing CI build option, pull request should follow.
BTW in case you have not noticed, if you want to make build quicker you can trigger git import process manually in launchpad, so you don't need to wait for next sync.
[https://code.launchpad.net/~wekan-team/wekan/+git/wekan-snap]

**Comment by xet7** [comment]
@kubiko 

Yes, I used trigger git import process yesterday, it worked great :)
