### ISSUE TITLE
Unable to set root-url with httpS

### ISSUE THREAD

**Issue by gbarre** [wekan/wekan-snap#22]
On Ubuntu 16.04.3 LTS :
`$ sudo snap install wekan`
`$ sudo snap set wekan root-url="https://wekan.home.priv" port="443"`
`$ sudo snap disable wekan`
`$ sudo snap enable wekan`

When I try to open with Safari (or Firefox) I see : "**Safari Can't Open the Page because Safari can't establish a secure connection to the server**".
DNS is ok, netstat on the server show it's listening on port 443.
I've try to change the port, It's always the same. If I replace "https" with "http" everything works.

Did I miss something ?

**Comment by xet7** [comment]
@gbarre 

Wekan does not include SSL, for that you need for example Caddy https://github.com/wekan/wekan-snap/issues/12 and ports exposed to Internet.

**Comment by gbarre** [comment]
Ok thank's.
