### ISSUE TITLE
After wekan installation with snap can not login 

### ISSUE THREAD

**Issue by ghost** [wekan/wekan-snap#23]
I am new to wekan and wanted to test it.
I installed wekan with snap and changed IP address as described in documentation.

But I can not login into system. No admin account can be enabled.
I tried to add admin user into MongoDB but it did not help.

**Comment by xet7** [comment]
@opkky 

Did you register new account in Wekan webpage, at http://ipadress/sign-up ? First registered user will become admin user.

**Comment by ghost** [comment]
@xet7 

Yes, I tried to register new account on Wekan webpage but got 3 errors:
- Internal Server Error
- Email already exist
- login already exist

Nothing happens if I press register button.

**Comment by xet7** [comment]
@opkky 

Internal server error is because you don't have email configured.

Email already exist because you have already registered.

Next you need to login at http://ipadress/sign-in
