### ISSUE TITLE
When Wekan snap is upgraded, root-url etc settings are lost

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#29]
@kubiko 

See https://github.com/wekan/wekan/issues/1471

root-url settings at wiki:
https://github.com/wekan/wekan-snap/wiki/Install#url-settings

Settings need to be applied again to get Wekan to work.

**Comment by xet7** [comment]
Workaround is to have some cron script check has the version changed or does the website work, and add those settings back.

**Comment by kubiko** [comment]
This should be now fixed with new pull request.
