### ISSUE TITLE
Ubuntu snap version of Wekan does not work in OpenVZ because of limited mounting privileges

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#30]
See https://github.com/wekan/wekan/issues/1203

**Comment by xet7** [comment]
I presume it's not possible to fix this.

**Comment by brianrc** [comment]
Damn!

Figured this out the hard way. :(

**Comment by brianrc** [comment]
Good news, my host updated to OpenVZ 7 from 6 and now it installs fine.

I can't get it to work alongside Vestacp though so can't confirm it totally works.
