### ISSUE TITLE
There is no route for path: /

### ISSUE THREAD

**Issue by scg001** [wekan/wekan-snap#32]
After deploying latest wekan snap (0.73.0) on a fresh install of ubuntu 16.04, I created one user, and on a new board created a long list of cards. When selecting a card the card window comes [at the very top](https://imgur.com/a/TULp2) of the page instead of showing next to the card itself as usual.

In Chrome console I get: ‘There is no route for path: /’ in boards page and when on a board i get ‘There is no route for the path: /b/rppAXm6iwLzYNqXAo/welcome-board’.

I suspect this could have something to do with URL routing, but that’s as far as my knowledge goes.

Does anyone have any ideas/suggestions please?

Thanks in advance :)

**Comment by xet7** [comment]
@apn3a 

Did you setup root-url ?
https://github.com/wekan/wekan-snap/wiki/Install

You need to setup also root-url again when Wekan update comes #29

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/1458 and https://github.com/wekan/wekan/issues/1481

**Comment by scg001** [comment]
@xet7

Yes. root-url is in place correctly, in fact cards do open.

**Comment by xet7** [comment]
@andresmanelli

Any ideas about that error?

**Comment by imreagocs-epicycle** [comment]
Found another routing error : 

d3c13763c9273588091c64026a12403e23b47898.js?meteor_js_resource=true:245 There is no route for the path: /b/8nQcvsGhnEDiDecpM/pharmacy-adt-board-beta/7ksDdEKENmCcn7RFB

**Comment by scg001** [comment]
did anyone have any luck with this please?

**Comment by andresmanelli** [comment]
@xet7 I get these errors in my local setup but I didn't notice any malfunction because of them. I don't know where they come from. Any hint?

Maybe the bug detail from the first comment is fixed by recent commits (card details)

@apn3a I don't really know if latest snap version includes those commits..

**Comment by scg001** [comment]
No longer experiencing issue with latest snap v0.80.
Was a bit of a challenge to transfer the DB between 0.62 to 0.80. But well worth it, v0.80 looks awesome!
Thanks for the great work 👍
