### ISSUE TITLE
Wekan release v0.75 failed publishing as snap because of executeable stack

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#33]
@kubiko 

I got this error when publishing Wekan v0.75 snap. Can you fix it ?

"Found files with executable stack. This adds PROT_EXEC to mmap(2) during mediation which may cause security denials. Either adjust your program to not require an executable stack, strip it with 'execstack --clear-execstack ...' or remove the affected file from your snap. Affected files: programs/server/npm/node_modules/meteor/rajit_bootstrap3-datepicker/lib/bootstrap-datepicker/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs functional-snap-v2_execstack"

https://forum.snapcraft.io/t/snap-and-executable-stacks/1812

Status: Manual review pending

https://dashboard.snapcraft.io/snaps/wekan/revisions/124/

**Comment by xet7** [comment]
It seems that somebody approved that release with manual review.

**Comment by kubiko** [comment]
I created now pull request which should fix this, so next time auto review should pass.
Snap is for now manually approved but this slows down and it will not be supported forever as this is otherwise security issue.
