### ISSUE TITLE
Swimlane rendering issue

### ISSUE THREAD

**Issue by vinistoisr** [wekan/wekan-snap#35]
Using snap version 0.77.0

Since the last update, all my boards are cutoff halfway.  Basically they are only showing the top default swimlane instead of taking up the whole screen.  I am not using swimlanes so the expected behaviour is that I click "List View" and the swimlanes go away, but still I only get the top half of the page. 

Is there a way to totally turn off the swimlane feature?

**Comment by kubiko** [comment]
@xet7 please confirm, but this seems like snap package unrelated behaviour.

**Comment by xet7** [comment]
@VinistoisR 

First update all snaps:

```
$ sudo snap refresh
```

Do you then have this revision 134 (or newer) of Wekan? This works for me, do you still have some issue?

```
$ sudo snap list
Name   Version           Rev   Developer  Notes
core   16-2.31.1         4110  canonical  core
wekan  0.77-16-ga23d933  134   xet7       -
```

**Comment by vinistoisr** [comment]
Yes that's the exact version I have, tried to refresh the snap and even terminate and rebuild the instance. 

![image](https://user-images.githubusercontent.com/36953653/36840868-5f022a40-1cfb-11e8-98ab-9c3a8a5926a7.png)

**Comment by xet7** [comment]
@VinistoisR 

Please add screenshots about this, what is the problem.

**Comment by vinistoisr** [comment]
Added a screenshot.  See how it is in list mode, but half the screen gets cut off, as if it was in swimlane mode.  Perhaps I am misunderstanding how it's supposed to work, is having a single, full screen board with no swimlanes no longer an option?
