### ISSUE TITLE
snap refresh => Services not restarted. 

### ISSUE THREAD

**Issue by Anuril** [wekan/wekan-snap#36]
Problem Described here: https://github.com/wekan/wekan/issues/1513

After each snap update, wekan is not running and has to be manually started by running: 

```
sudo systemctl restart snap.wekan.mongodb
sudo systemctl restart snap.wekan.wekan
```

This happens since I installed the wekan snap @122.

**Comment by kubiko** [comment]
Ups, problem when snapd calls stop start too fast, systemd seems to ignore start part.
Changed logic for restart effort. I will unnecessary restart mongodb and caddy at install and refresh in quick sequence, but will it will run.
Pull Request here: [1514](https://github.com/wekan/wekan/pull/1514)
