### ISSUE TITLE
Wekan Snap does not work on Debian 9 for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#40]
I did get errors about snap socker. I did try to fix it with info from related issues at https://github.com/Microsoft/WSL/issues/534 https://github.com/Microsoft/WSL/issues/534 but with no success.

![wekan-snap-debian-windows-not-working](https://user-images.githubusercontent.com/15545/37738299-458c1886-2d5f-11e8-919f-54bc0f0ff6a2.png)

**Comment by xet7** [comment]
Wekan works with source install on Windows SubSystem for Linux, so it's enough for development.
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/rebuild-wekan.sh

**Comment by kubiko** [comment]
Yeah at the moment snap packages don't work in Windows Linux sub system. Kernel Linux emulation is not there yet with feature set to allow full security continent and other needed features
