### ISSUE TITLE
Disappeared cards after moving issues to another board (bug already fixed, but need recovery for old cards)

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [wekan/wekan-snap#41]
Some versions ago (<= 0.76) there was a bug, which prevented cards from showing up after moving them from another board - while using swimlanes. 
They still show up when I disable swimlanes, but when I activate the lanes again, they disappear again.

Can I somehow save all cards, so they show up again? 

One workaround is to deactivate swimlanes, move each single card again (via the move card option) and then enable swimlanes again - but this is not really practicable when you have more than 100 cards :/

Any hints? Thank you very much!

**Comment by xet7** [comment]
@lichtamberg 

Can you export them from old version as Wekan JSON, and import to new Wekan ?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Not really, since I have no time for testing these things right now.. I will close this issue and look at it when I have more time again, in the meantime we are finishing the tickets by toggling the swimlines, which works for us..
