### ISSUE TITLE
Links to cards not working

### ISSUE THREAD

**Issue by txelu** [wekan/wekan-snap#43]
Links to cards stop working I guess after a Wekan upgrade. What I get now when I try to use one link to card is an empty grey screen as when Wekan tries to refresh its contain. If I look at the javascript console in the browser I find the following error:

`There is no route for the path: /b/4hAkFK3ncv4kAd8Fg/support/2smKKoZfeQQEanFGs`

That happens also if I open a card and then I try to reload it by pressing enter key on its own URL in the browser. On the other hand, when I'm at the board and I try to reaload its URL in the same way I get a similar error (`There is no route for the path: /b/4hAkFK3ncv4kAd8Fg/support` in this case), but the board is finally shown.

I have already checked that the root-url is set as expected as instructed in #32 (and I tried setting it again, with no success) so I have no clue on what else to check. Is there any logs that I could check to know what's happening?

Thanks!

**Comment by xet7** [comment]
@txelu 

What snap version? Wekan v0.83 revision 164 works for me. You can update with `sudo snap refresh`

```
$ sudo snap list
Name   Version    Rev   Tracking  Developer  Notes
core   16-2.32.3  4407  stable    canonical  core
wekan  0.83       164   stable    xet7       -
```

**Comment by txelu** [comment]
The version I'm using is now 0.85 (I guess it was updated tonight):
```$ sudo snap list
Name               Version    Rev   Tracking  Developer   Notes
core               16-2.32.3  4407  stable    canonical   core
lxd                3.0.0      6729  stable    canonical   -
rocketchat-server  0.63.1     1248  stable    rocketchat  -
wekan              0.85       166   stable    xet7        -
```

**Comment by Comanchspb** [comment]
I've same issue with 0.85 rev 166 by Snap

**Comment by xet7** [comment]
Moved to wekan/wekan#1596
