### ISSUE TITLE
Wekan Snap build failed: DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#45]
@kubiko 

I did try to make Wekan release, and got errors in todays's snap build log:
https://launchpadlibrarian.net/366543875/buildlog_snap_ubuntu_xenial_amd64_wekan-devel_BUILDING.txt.gz

```
DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn7 for more information.
DEPRECATED: The 'build' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn8 for more information.
DEPRECATED: The 'install' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn9 for more information.
```

Could you fix build, so it works again?

**Comment by xet7** [comment]
I did get 404 error on those deprecation notice links.

**Comment by xet7** [comment]
@stolowski

Are these really deprecated, or should [Wekan's snapcraft.yaml](https://github.com/wekan/wekan/blob/devel/snapcraft.yaml) be fixed somehow?

**Comment by kyrofa** [comment]
These are indeed deprecated, but looks like we missed a docs deploy, sorry about that! While we fix that, you can read the deprecation notices [here](https://github.com/canonical-docs/snappy-docs/blob/master/deprecation-notices/dn7.md). Note however that these aren't errors, just warnings, and this isn't something we intend to break anytime soon, just want to suggest people take a look at the "new" way of doing things. Looks like your build failed with a proxy error.
