### ISSUE TITLE
Wekan Snap install default config (local server)

### ISSUE THREAD

**Issue by mosiman** [wekan/wekan-snap#47]
On Wekan version 0.94.0, node version v8.11.1 (4.9.96-1 MANJARO), everything works up until I try to click on a card, looks like a bad link? (Not sure if proper terminology). I get a 'refused to connect' error.

I say this because the default root-url is `http://127.0.0.1` and the port exposed is `8080`. However, setting the root-url to contain the port, i.e., 

`sudo snap set wekan root-url="http://127.0.0.1:8080"` 

fixes the issue. Not sure if the default config works fine for others, though. 

On a related note (but probably more on the Snapd side), setting the `root-url` key doesn't seem to be persistent (i.e., have to start snapd in systemctl and redo the command `sudo snap set wekan root-url="http://127.0.0.1:8080" whenever I shut down the computer). Is there a way to make this persistent? 

Cheers.

**Comment by mosiman** [comment]
haha... Just saw that the main page even says that [URL settings have to be configured](https://github.com/wekan/wekan-snap/wiki/Install) first.

Anyways, it looks like the changes are persistent if I enable the snapd service with systemctl
`sudo systemctl enable snapd.service`
so, my bad for opening an issue. Hope this helps someone.

**Comment by webolizzer** [comment]
same problem with wekan 4.49

**Comment by xet7** [comment]
@webolizzer 

What do you mean?

**Comment by webolizzer** [comment]
@xet7

i have installed wekan 4.49 on my ubuntu 16 PC via terminal with command:

$ sudo snap install wekan 

after that i have opened http://127.0.0.1:8080/ url in chrome browser

i have created an user and then a board

then i have created a card inside of the board, and by clicking on the card the browser has showed me error "this link does not exists"

after that i have changed the url settings in terminal with command:

$ sudo snap set wekan root-url="http://127.0.0.1:8080"

and this has fixed the issue

**Comment by xet7** [comment]
@webolizzer 

But it's not any "problem". It is a normal way to install Wekan.

For example, if you don't have anything running on port 80, you can set this way, so wekan is at http://localhost
```
sudo snap set wekan root-url='http://localhost'
sudo snap set wekan port='80'
```
Or, you can get your local IP address with this command:
```
ip address
```
So for example set it this way, so other computers and mobile devices at your local network can access Wekan and open cards correctly at http://192.168.0.100 , you can also reserve static IP for your Wekan server computer MAC address at your Internet router that usually has config at http://192.168.0.1 .
```
sudo snap set wekan root-url='http://192.168.0.100'
sudo snap set wekan port='80'
```
More info at https://github.com/wekan/wekan/wiki/Settings
