### ISSUE TITLE
does not work debian 9

### ISSUE THREAD

**Issue by perchibald** [wekan/wekan-snap#48]
$snap version
snap    2.32.8
snapd   2.32.8
series  16
debian  9
kernel  4.9.0-6-amd64

$snap list
Name   Version    Rev   Tracking   Developer  Notes
core   16-2.32.8  4650  stable     canonical  core
wekan  1.02       202   candidate  xet7       devmode

$systemctl status snap.wekan.mongodb.service
● snap.wekan.mongodb.service - Service for snap application wekan.mongodb
   Loaded: loaded (/etc/systemd/system/snap.wekan.mongodb.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-05-28 16:00:29 +05; 28min ago
  Process: 780 ExecStart=/usr/bin/snap run wekan.mongodb (code=exited, status=1/FAILURE)
 Main PID: 780 (code=exited, status=1/FAILURE)

май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Main process exited, code=exited, status=1/FAILURE
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Unit entered failed state.
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Service hold-off time over, scheduling restart.
май 28 16:00:29 wekan systemd[1]: Stopped Service for snap application wekan.mongodb.
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Start request repeated too quickly.
май 28 16:00:29 wekan systemd[1]: Failed to start Service for snap application wekan.mongodb.
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Unit entered failed state.
май 28 16:00:29 wekan systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'

$systemctl status snap.wekan.wekan.service
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-05-28 16:00:40 +05; 29min ago
  Process: 1313 ExecStart=/usr/bin/snap run wekan (code=exited, status=1/FAILURE)
 Main PID: 1313 (code=exited, status=1/FAILURE)

май 28 16:00:39 wekan systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
май 28 16:00:39 wekan systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
май 28 16:00:39 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
май 28 16:00:40 wekan systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
май 28 16:00:40 wekan systemd[1]: Stopped Service for snap application wekan.wekan.
май 28 16:00:40 wekan systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
май 28 16:00:40 wekan systemd[1]: Failed to start Service for snap application wekan.wekan.
май 28 16:00:40 wekan systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
май 28 16:00:40 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.

**what logs can I still show?**

**Comment by xet7** [comment]
Reboot.

Then do:
```
sudo snap remove wekan

sudo snap install wekan
```

**Comment by perchibald** [comment]
magic!!! thx)
