### ISSUE TITLE
[Question] Where are located datas (BDD, files...) to set up a dedicated partition?

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan-snap#49]
Hello,

I want to use snap to install Wekan but I am quite a noob in snap usage... I would like to set up a dedicated partition for Wekan data (BDD, files...). On which folder should I set up a partition ?

- /snap
- /var/lib/snapd
- /var/snap

For instance, I intended to set up a dedicated partition on /var/lib/docker for a Docker installation.

Regards.

**Comment by xet7** [comment]
/var/snap
