### ISSUE TITLE
Error message is not complete in snap

### ISSUE THREAD

**Issue by jameswangcnln78** [wekan/wekan-snap#5]
I used command like "sudo systemctl status snap.wekan.wekan" and got incomplete error log like below:

>    Active: active (running) since 五 2017-07-07 09:00:15 CST; 1h 35min ago
>  Main PID: 30689 (wekan-control)
>     Tasks: 11
>    Memory: 131.3M
>       CPU: 10.094s
>    CGroup: /system.slice/snap.wekan.wekan.service
>            ├─30689 /bin/bash /snap/wekan/8/bin/wekan-control
>            └─30714 /snap/wekan/8/bin/node main.js
> 
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at packages/ddp-server/livedata_server.js:719:19
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at packages/ddp-server/livedata_server.js:717:40
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at packages/ddp-server/livedata_server.js:715:46
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     - - - - -
> 7月 07 10:26:21 james-ThinkPad-E450 snap[30689]:     at Error (native)

I wonder the way to find complete error log message. Thanks

**Comment by xet7** [comment]
@jameswangcnln78 

Wekan snap detailed log:

```
$ sudo journalctl -u snap.wekan.wekan.service
```

All wekan snaps detailed logs:

```
$ sudo journalctl -u snap.wekan.*
```

These are at:
https://github.com/wekan/wekan-snap/wiki/Troubleshooting

Are you trying to debug something ?
