### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ghost** [wekan/wekan-snap#53]
Hey,

i installed wekan over snap and run into the following problem:

> Jul  6 15:13:04 wekan1 wekan.wekan[13350]: TypeError: Boards.forEach is not a function
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at Object.Migrations.add [as migrationCallback] (server/migrations.js:156:10)
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at packages/idmontie_migrations.js:238:17
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at Function.time (/snap/wekan/230/programs/server/profile.js:309:28)
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at /snap/wekan/230/programs/server/boot.js:423:13
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at /snap/wekan/230/programs/server/boot.js:464:5
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at Function.run (/snap/wekan/230/programs/server/profile.js:510:12)
Jul  6 15:13:04 wekan1 wekan.wekan[13350]:     at /snap/wekan/230/programs/server/boot.js:462:11

**Comment by xet7** [comment]
@DeroSavage 

Update to newest Wekan. To do it manually:
```
sudo snap refresh
```

**Comment by xet7** [comment]
@DeroSavage 

Currently Wekan v1.18 is building, it has more fixes, so try updating later today. Usually snap upgrades automatically also.
