### ISSUE TITLE
Single Sign On support?

### ISSUE THREAD

**Issue by rasos** [wekan/wekan-snap#56]
There are several attempts to offer SSO for Wekan:

- oAuth2: https://github.com/wekan/wekan/pull/1578 - PR needs settings added as environment variables
- LDAP: https://github.com/wekan/wekan/issues/119 - refactor RocketChat code
- SAML: ?

It looks like the lowest hanging fruit is oAuth2. Will this feature after a successful PR be automatically available in the snap version?

**Comment by kubiko** [comment]
unless there are some unexpected complication it should just work in snap, it's running from same code.

Once PR is merged to master, there should be new build available in edge channel (usually within 6 hours) to test it
you can switch to test edge channel by:
$ snap switch wekan --edge; snap refresh wekan

**Comment by konsumate** [comment]
LDAP is not SSO - with LDAP you need to enter your username/password everytime your session expires.

**Comment by xet7** [comment]
Those PR's may have some settings missing so they can be configured with snap commands (or Admin Panel). After those are added, PR's will be merged.
