### ISSUE TITLE
Build service can't download npm@latest

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#58]
@kubiko 

https://forum.snapcraft.io/t/build-error-npm-latest/6573

**Comment by xet7** [comment]
@stolowski 

Is there any working way to currently build Wekan snap?
I have tried:

- Canonical’s build service
- docker
- lxc
- vagrant / VirtualBox Ubuntu 16.04 VM

And everything is broken.

**Comment by kubiko** [comment]
@xet7  I will have a look, in the mean time I'm testing manual local build if that works
I will let you know

**Comment by kubiko** [comment]
@xet7 it seems to be building fine locally, I'm just pushing devel build to store, and I will also build 1.23 from tag
You will need to release those, I will only push them to the store to be available there

**Comment by xet7** [comment]
@kubiko 

How did you build them locally?

**Comment by kubiko** [comment]
@xet7 you can use any Ubuntu 16.04 machine(server or desktop), just install snapcraft. If you are running 18.04 or other releases, it's best to use lxc, I will prepare you short script for that case
Then:
$ snap install --classic snapcraft
and run within source tree
$ snapcraft
it will build snap package, no need to install any dependencies snapcraft will take care of everything
to clean, run
$ snapcraft clean

I have also now uploaded 1.23 release so once checked you can also release that one

**Comment by xet7** [comment]
@kubiko 

When I tried to build in lxc, I did get these errors:
```
Fetched 116 kB in 0s (0 B/s)                                                                                                                                                                          
Pulling wekan 
Downloading 'node-v8.11.3-linux-x64.tar.gz'[=====================================================================================================================================================] 100%
npm --cache-min=Infinity install --global npm
/root/build_wekan/parts/wekan/install/bin/npm -> /root/build_wekan/parts/wekan/install/lib/node_modules/npm/bin/npm-cli.js
/root/build_wekan/parts/wekan/install/bin/npx -> /root/build_wekan/parts/wekan/install/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.3.0
added 283 packages, removed 363 packages and updated 41 packages in 19.446s
npm --cache-min=Infinity install --global node-gyp
/root/build_wekan/parts/wekan/install/bin/node-gyp -> /root/build_wekan/parts/wekan/install/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@3.7.0
added 105 packages from 67 contributors in 8.563s
npm --cache-min=Infinity install --global node-pre-gyp
/root/build_wekan/parts/wekan/install/bin/node-pre-gyp -> /root/build_wekan/parts/wekan/install/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
+ node-pre-gyp@0.10.3
added 66 packages from 25 contributors in 3.781s
npm --cache-min=Infinity install --global fibers@2.0.0

> fibers@2.0.0 install /root/build_wekan/parts/wekan/install/lib/node_modules/fibers
> node build.js || nodejs build.js

sh: 1: node: Permission denied
module.js:328
    throw err;
    ^

Error: Cannot find module '/root/build_wekan/parts/wekan/install/lib/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-04T15_57_32_390Z-debug.log
Failed to run 'npm --cache-min=Infinity install --global fibers@2.0.0' for 'wekan': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Stopping local:snapcraft-supportably-unsquirming-apollo
```
Do you have idea how to fix them?

It would also be nice if canonical's snap build server could be fixed.

**Comment by xet7** [comment]
@kubiko 

I was able to build .snap package with clean install of Ubuntu 16.04.5, with snapcraft command. So now building manually works for me.

**Comment by xet7** [comment]
I needed to build snapcraft from source, to get Wekan snap package built.
https://github.com/wekan/wekan-snap/wiki/Making-releases

**Comment by cjwatson** [comment]
I have a fix for the Launchpad snap build service awaiting deployment, so once https://bugs.launchpad.net/rutabaga/+bug/1781970 is marked "Fix Released" you should be able to retry that.

**Comment by xet7** [comment]
@cjwatson 

I got this error in email:

> Launchpad uploaded this snap package to the store, but the store failed to scan it:
> DatabaseError: pgbouncer cannot connect to server
server closed the connection unexpectedly
> This probably means the server terminated abnormally
> before or while processing the request.
> https://launchpad.net/~wekan-team/+snap/wekan-devel/+build/330020
> Your team wekan-team is the requester of the build.

**Comment by cjwatson** [comment]
That was a transient problem in the store.  Unfortunately the store upload retry logic is a bit buggy and broke with "A file with this exact same content has already been uploaded".  I have some plans for fixing the buggy logic here, but in the meantime I suggest just requesting a fresh build.

**Comment by xet7** [comment]
Build service works now.

There is also new release of snapcraft with fix, although I have not tested it yet.
