### ISSUE TITLE
cannot locate the core or legacy core snap

### ISSUE THREAD

**Issue by rafaelsoaresbr** [wekan/wekan-snap#59]
Hello, I'm trying to run wekan on Oracle Linux 7.5, following CentOS instructions I was able to install snapd then:

`sudo snap install wekan`

 ```
error: cannot perform the following tasks:
 - Run install hook of "wekan" snap if present (run hook "install":
 -----
 cannot locate the core or legacy core snap (current symlink missing?): No such file or directory
 cannot read expected data from eventfd: Interrupted system call
 -----)
```

What file or directory is it trying to access?

**Comment by kubiko** [comment]
Let's check some basics, do you have 
what do you get from `$ snap list`?
What is content of:
`/snap/`
If core snap is missing, are you able to install it manually:
`$ snap install core`

**Comment by rafaelsoaresbr** [comment]
`$ snap list`
```
Name  Version  Rev   Developer  Notes
core  16-2.35  5328  canonical  core
```
`$ ls -la /snap`
```
total 8
drwxr-xr-x.  4 root root   43 Set  6 08:28 .
dr-xr-xr-x. 18 root root 4096 Set  5 11:05 ..
drwxr-xr-x.  2 root root    6 Set  6 08:28 bin
drwxr-xr-x.  3 root root   33 Set  5 14:16 core
-r--r--r--.  1 root root  548 Set  5 11:05 README
```
Thanks for quick reply.

**Comment by alexdndz1** [comment]
Hi.

Have you solved this problem?

**Comment by alexdndz1** [comment]
sudo yum install yum-plugin-copr -y

sudo yum copr enable ngompa/snapcore-el7 -y

sudo yum install snapd -y

sudo systemctl enable --now snapd.socket

sudo ln -s /usr/libexec/snapd /usr/lib/

sudo ln -s /var/lib/snapd/snap /snap

sudo systemctl start snapd

sudo systemctl status snapd

sudo snap install core

snap info wekan

sudo snap install wekan

**Comment by alexdndz1** [comment]
You can close the problem.
