### ISSUE TITLE
Changing port is not working as it should?

### ISSUE THREAD

**Issue by rolandixor** [wekan/wekan-snap#65]
I followed these instructions:

https://askubuntu.com/a/1081930/1992

try to set using root url of Wekan with following

sudo snap set wekan root-url="http://localhost:5001"
restart your snap of Wekan again

sudo systemctl restart snap.wekan.wekan
and check your url of Wekan

sudo snap get wekan

It worked at first, but then I realized that wekan was having issues with the user I'd created (the only user). At that time, I realized wekan was on the fritz - period, wouldn't even restart. So, I removed the snap, cleared all configuration files, and reinstalled.

Now, wekan is stuck on port 8080, instead of 8081, as I instructed it to use. Is there no way to get the port change to "stick"?

**Comment by xet7** [comment]
@rolandixor 

Did you change port also?
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

```
sudo snap set wekan root-url='http://localhost:5001'

sudo snap set wekan port='5001'
```

**Comment by rolandixor** [comment]
EDIT: Tried it again - and now it works. I'll see if it sticks.

In the past, it worked until I restarted wekan. I'll close for now, and reopen if it happens again on the next reboot.

**Comment by hkocaoglu** [comment]
Hey everyone. I have the same issue but i am using presinstalled version from Univention site. So i  logged in server and snap is not installed ? What should i do to set root-url ? 

Should i install snap and run the command or , i should edit some files ? 

regards

**Comment by xet7** [comment]
@hkocaoglu 

Univention has Docker version of Wekan, and these web-based ROOT_URL settings:
https://github.com/wekan/univention/issues/1#issuecomment-532644339

You should not install Snap, when using Univention Wekan. Univention Wekan is integrated directly to Univention user management of normal and admin users, as is mentioned at:
https://github.com/wekan/wekan/wiki/Platforms and https://github.com/wekan/univention

For other Univention Wekan related questions, please add to https://github.com/wekan/univention/issues . Thanks!
