### ISSUE TITLE
Feature Request: Use Snap channels to separate stable/beta builds

### ISSUE THREAD

**Issue by nmd3** [wekan/wekan-snap#67]
Would it be possible to begin using channels for snap releases as documented here: https://forum.snapcraft.io/t/channels/551

Currently Wekan channels are all the same release, and often there are multiple simultaneous releases to the point where I don't have the "latest" version despite using snap:
![image](https://user-images.githubusercontent.com/44180132/47433474-8dc9ff00-d76e-11e8-88e9-26c701a1701e.png)

What is actually more concerning to me is introducing new features to my users that might require a learning curve. It would be great to see most of the daily updates occurring on a candidate or beta channel and then added to stable releases on a schedule that I can anticipate (e.g. ~1/month). 

I love all of the work that you're doing, I'm just worried that introduction/removal of new features so rapidly is going to confuse my users and potentially break things (e.g. I've instructed them not to use custom fields because I don't want to repair JSON files every time they decide to delete the custom fields; I've also told them to avoid using subtasks due to the way the feature behaves). The latest version reintroduced rules, which canbe a great feature, but might be one that requires a learning curve.

Maybe an alternative to this is admin ability to disable certain features.

**Comment by xet7** [comment]
I'm using beta/edge etc channels when there is something that could be broken.

**Comment by nmd3** [comment]
@xet7 are the stable/edge channels supposed to be separate now? Per https://wekan.github.io/ the stable release is 2.35, but I'm seeing 2.42 across all channels when I run `snap info wekan` on my installation:

> refresh-date: today at 03:35 UTC
> channels:
>   stable:    2.42 2019-03-07 (467) 133MB -
>   candidate: 2.42 2019-03-07 (467) 133MB -
>   beta:      2.42 2019-03-07 (467) 133MB -
>   edge:      2.42 2019-03-07 (468) 133MB -
> installed:   2.42            (467) 133MB -

**Comment by xet7** [comment]
@nmd3 

I updated stable version to be 2.42 at website.

The reason why 2.35 was marked stable was that after it there was major changes that did bring some new bugs, but many of those are already fixed, and there is no plans to remove any features and fixes that are at 2.42.

Some months ago there really was separate stable and edge, because new features at edge were broken. When they did get more usable, they did get merged to stable.

But now I'm thinking, would there still be a need to be separate stable and edge.

**Comment by xet7** [comment]
I have used separate channels when needed, as I did for some days recently.
