### ISSUE TITLE
Question: what about CORS ?

### ISSUE THREAD

**Issue by loic74** [wekan/wekan-snap#69]
How to enable Cross Origin Resource Sharing on snap version ?

I get this error message when I try to add a card via the API:
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Thanks ;-)

**Comment by loic74** [comment]
Thank you for this feature. Unfortunately, this still doesn't work for me with 1.80 version, after a sudo snap set wekan cors='*'...
`Access to XMLHttpRequest at **** from origin **** has been blocked by CORS policy: Request header field Authorization is not allowed by Access **** Control-Allow-Headers in preflight response.`

**Comment by xet7** [comment]
snap config has extra commas `,` so I will remove them, maybe cors will work after that in next Wekan release.

**Comment by xet7** [comment]
@loic74

Please test Wekan v1.81 is this now fixed ?

**Comment by xet7** [comment]
@loic74

Please test Wekan v1.82 , is this now fixed ?

**Comment by loic74** [comment]
Same error with 1.82. 
`Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

Here is my code:

`var params = {`
			 ` "title": "test",`
			 ` "description": "add a card",`
			  `"authorId": "HBzQr4mCvpgjMYbzv",`
			 ` "swimlaneId": "FyRMVhQ4YnntiPxXP"`
			`};`

`var xhr = new XMLHttpRequest();`
				`xhr.open("POST", url);`
				`xhr.setRequestHeader('Authorization', 'Bearer ' + 'xxx...');`
				`xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");`
				`xhr.send(JSON.stringify(params));`

**Comment by xet7** [comment]
@loic74 

With curl I see that * header is in wekan. Did you [login to API first](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-json) first to get valid bearer key, before doing API request?

For complete example, see https://github.com/wekan/wekan-gogs

**Comment by xet7** [comment]
Login needs to be made with username and password of admin that has access to Admin Panel.

**Comment by loic74** [comment]
> With curl I see that * header is in wekan. Did you login to API first first to get valid bearer key, before doing API request?

Not in the same script, but I use a valid token (generated via Postman) for testing. Moreover, by using the same token via Postman, card creation works fine.


> Login needs to be made with username and password of admin that has access to Admin Panel.

Yes, I use admin credentials.

**Comment by xet7** [comment]
Please give more descriptive details what is the problem.

**Comment by loic74** [comment]
Thank you for your help. Finally, I changed my method. Instead of executing the code client-side , I use a php page that executes the code server-side. It works fine.

**Comment by erezsdev** [comment]
Is there any fix for this? I am using the latest version and still setting cors='*' not working, which makes the API useless if not using from the same host.

`Access to XMLHttpRequest at 'http://****:3001/users/login' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by xet7** [comment]
@erezsdev 

Yes, see https://github.com/wekan/wekan/pull/2429 that is already in Wekan
