### ISSUE TITLE
can't open cards due to card URL being 127.0.0.1 instead serverIP:port#

### ISSUE THREAD

**Issue by dulhaver** [wekan/wekan-snap#7]
related with this issue https://github.com/wekan/wekan/issues/472

### setup
- running the wekan snap on a local ubuntu server
- accessing wekan from local network on the server's IP addresss, port 8080 (like `172.20.14.233:8080` i.e.)

### error
- when opening a card the URL is set to **127.0.0.1**/b/board-id/board-name/card-id (which is the snaps internal local ip) instead of the server's IP. So the card can not be opened.
- manually changing the IP in the browser to **172.20.14.233:8080**/b/board-id/board-name/card-id allows opening the card as expected

**Comment by dulhaver** [comment]
this is caused by the so called `ROOT_URL` being internally hard wired to 127.0.0.1 apparently (not sure whether terminology is completely accurate, but I guess you may be able to get my drift)

### solution
1. change the ROOT_URL to the same IP:port as your server  
`sudo snap set wekan root-url=http://172.20.14.233:8080`  
2. restart wekan with: `sudo systemctl restart snap.wekan.wekan`  
  
thanks @xet7 for pointing into the right direction in this regards

**Comment by xet7** [comment]
I added more detailed documentation to [Wekan snap wiki Install page](https://github.com/wekan/wekan-snap/wiki/Install) and [Wekan snap readme](https://github.com/wekan/wekan-snap) so this information would be found more easily. I also changed Wekan snap install links on [Wekan releases](https://github.com/wekan/wekan/releases) and [Wekan Platforms](https://github.com/wekan/wekan/wiki/Platforms).

**Comment by dulhaver** [comment]
perfect, I wanted to do something like that, but didn't get to it yet

**Comment by xiaohelong** [comment]
Chinese Language as follows
wekan 看板系统(仿trello)0.49 虚拟机文件(virtualbox vmware images) https://drive.google.com/file/d/0B_ZOwu5Ug5UgS0VoZF9yNWJlcDQ/edit 0.49 virtualbox 虚拟文件下载，开箱即用。
我下载并安装试用，解决了存在的问题。ova支持vmware，百度云下载地址http://pan.baidu.com/s/1jHYeiMi

特别注意：在系统中需要设定ROOT变量为设定的ip或者域名，否则页面中很多地方会全是localhost
在/home/wekan/repos/run-wekan.sh中将ROOT_URL和端口改成本机IP和需要的端口即可解决页面很多链接是localhost基地址的问题。改完后，重启计算机。
contents from 0.49 virtualbox images source /home/wekan/repos/run-wekan.sh
while true; do
cd /home/wekan/repos/wekan/.build/bundle
export MONGO_URL='mongodb://127.0.0.1:27017/admin'
# Production: https://example.com/wekan
# Local: http://localhost:3000
export ipaddress=$(ifdata -pa eth0) #auto get ip here, 这是自动获取系统IP地址的命令，默认是注释掉的。
export ROOT_URL='http://10.0.2.15' #set ip here
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
# This is local port where Wekan Node.js runs, same as below on Caddyfile settings.
export PORT=80
node main.js
done

**Comment by mydoghasworms** [comment]
@xet7 The `root-url` solution works fine when wekan is being accessed directly.
In my case, however, it is behind an nginx service where I use proxy_pass to forward requests to the wekan service.
In that case, everything works fine until you click on a card link; then it actually redirects the browser to the host and port of the wekan server. Why does the card link even require building up a URL using a separate setting? Surely just specifying "://<link>" should be sufficient?

**Comment by xet7** [comment]
@mydoghasworms 

root-url is how https://meteor.com Javascript framework works by design. root-url specifies how Wekan makes URL to card. If you have nginx providing https://example.com/wekan , proxying to localhost, and root-url is not https://example.com/wekan, then url goes to wrong address and card does not open, 
see https://github.com/wekan/wekan/wiki/Settings

**Comment by mydoghasworms** [comment]
@xet7 Of course, you are right. I should have set the URL of the server hosting NGINX in my case.

However, I still wonder why you couldn't just use a relative URL for the card instead of an absolute one?

**Comment by xet7** [comment]
@mydoghasworms 

Absolute root-url is how https://meteor.com Javascript framework works by design.

**Comment by darkworks** [comment]
solution is simple just use your server ip or domain address instead of 127.0,0.1 in nginx or apache config for wekan , also update your wekan start up environment root url with your server ip instead of local

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Settings

**Comment by frantzstaboeeg** [comment]
I'm struggling with this as well. Im running snap with nginx within local lan.

so that is option 3 in https://github.com/wekan/wekan/wiki/Settings 
Nginx is set up using port 8081 and wekan with 8080
Im using wekan snap version 1180

I've set the root-url:
sudo snap set wekan root-url='http://10.12.12.178:8080'
sudo systemctl restart snap.wekan.mongodb
sudo systemctl restart snap.wekan.wekan

sudo snap get wekan
port       8080
root-url   http://10.12.12.178:8080


When viewing cards within a board a get redirected to 127.0.0.1

I have inspected the html code and redirection to boards works as it is using relative urls, the redirection to card use abolute urls paths which fails for me.
<a class="minicard-wrapper js-minicard ui-droppable" href="http://127.0.0.1/b/dXSfstjGdr6uivepL/ .....

Its seems for me that wekan is not using the root-url at all.

I've started creating cards when the server was running with localhost ip. Could this be an issue?

Regards

**Comment by frantzstaboeeg** [comment]
My wekan nginx conf looks like this:

cat /etc/nginx/conf.d/wekan.conf
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 8081;
    server_name 10.12.12.178;
    if ($http_user_agent ~ "MSIE" ) {
        return 303 https://browser-update.org/update.html;
    }
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
    }
}

**Comment by xet7** [comment]
@frantzstaboeeg 

You don't need Nginx at all when using local network and http.

You should look what is your Wekan server IP address with command:
```
ip address
```
For example, if your IP address is 192.168.0.100, use commands:
```
sudo snap set wekan root-url='http://192.168.0.100:8080'
sudo snap set wekan port='8080'
```
And stop and disable Nginx:
```
sudo systemctl stop nginx
sudo systemctl disable nginx
```
Although when there are no other webservers running, I prefer using port 80:
```
sudo snap set wekan root-url='http://192.168.0.100'
sudo snap set wekan port='80'
```
Usually Nginx/Apache/Caddy is used only when it provides SSL/TLS for domain in front of Wekan, when Wekan is available through Internet with Nginx/Apache/Caddy serving ports 80 (redirect to SSL/TLS) and 443 (SSL/TLS). In that case, settings are like this:
```
sudo snap set wekan root-url='https://boards.example.com'
sudo snap set wekan port='8080'
```
So Nginx/Apache/Caddy proxies from SSL/TLS 443 to localhost port 8080.

**Comment by frantzstaboeeg** [comment]
Thanks for fast reply.

The local ip is 10.12.12.178:
ip addr
wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 30:24:32:cd:d5:c5 brd ff:ff:ff:ff:ff:ff
    inet 10.12.12.178/24 

I thought i needed nginx to host local static files like images i use in the markdown?
Anyway now i've stop nginx

sudo systemctl status nginx
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)

I also cleared the firefox cookies etc

sudo snap set wekan root-url='http://10.12.12.178:8080'
sudo snap set wekan port='8080'

The behavior is  the same. The browser  do not point to the correct address for cards.
I also connected to the wekan server from  another computer in the same network. It displays 404 page when clicking on cards as it uses the 127.0.0.1 address.

http://127.0.0.1/b/dXSfstjGdr6uivepL/fsi-qualification-program/5hS4gexKovHSTNaRr

If i manually edit the url in the browser address field 
http://10.12.12.178:8080/b/dXSfstjGdr6uivepL/fsi-qualification-program/5hS4gexKovHSTNaRr
The correct card page is displayed. 

Is there an other method to debug this?

**Comment by xet7** [comment]
@frantzstaboeeg 

If you have manually added direct links to files or cards, and those old links still have 127.0.0.1 in them, then those do not work. Changing root-url only affects opening cards in general, it does not search-replace all card content.

You can use [nosqlbooster GUI](https://github.com/wekan/wekan/wiki/Backup) to edit database.

**Comment by frantzstaboeeg** [comment]
I understand, but I only click on the card using the mouse button. For instance if i add a new card and then  click on it afterwards it points to the 127.0.0.1. Could it  be that the wekan snap app  is not using the root_url at all, but collect the address from some other location? I was considering installing the wekan natively and see it it behaves different.

**Comment by xet7** [comment]
@frantzstaboeeg 

I think it depends are there any typos in settings.
For example, this is correct:
```
sudo snap set wekan root-url='http://10.12.12.178:8080'
sudo snap set wekan port='8080'
```
So Snap settings are lowercase, with `-` minus between settings words. Not underscore `_`.

For Docker and Source, it's uppercase and underscore, without quotes, like:
```
export ROOT_URL=http://10.12.12.178:8080
export PORT=8080
```

**Comment by frantzstaboeeg** [comment]
Don't think its a typo.  I have copied the text from above and it behaves the same. However, I cloned the git repo and runned the rebuild-wekan.sh. script
on a seperat port 4003. http://10.12.12.178:4003. Here the card linking behaves correctly.  Could it be that there is a bug in the snap release?
