### ISSUE TITLE
How to define the default authentication method to LDAP ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan-snap#70]
**Server Setup Information**

* Did you test in newest Wekan? : yes
* Wekan version: 1.80
* Deployment Method: Snap

Hello,

Now the dropdown has been removed from the login page, what is the snap variable to define LDAP as the default authentication method ? (I didn't find it in [snap config file](https://github.com/wekan/wekan/blob/master/snap-src/bin/config))

New users (from LDAP) can not login for the first time to the application.
Only existing users can still log in.

Regards.

**Comment by xet7** [comment]
dropdown has been added back in newest Wekan v1.82
