### ISSUE TITLE
E-Mail doesn't work after snap update

### ISSUE THREAD

**Issue by spassig** [wekan/wekan-snap#78]
I use Snap-Update on Ubuntu 16.04.3 LTS for Wekan.

After every Snap-Update E-Mails from Wekan doasn't work any more. I need to go to the E-Mail-Settings and re-enter the password to get E-Mails working again.

BTW: Thanks for this great tool. I switched from Trello to Wekan for privacy reasons (EU-DSGVO) a couple of months ago and do not miss anything important.

**Comment by cyberfarer** [comment]
I have a related issue. 

I run Wekan as a snap on Ubuntu 16.04.4 LTS. Every morning I must go in to Admin Panel, Email and press Save or emails are not sent. I have set up a cron job run snap set commands every morning to address this.

**Comment by xet7** [comment]
@cyberfarer 

What cron job you use? Source?

**Comment by spassig** [comment]
@cyberfarer I would also like to know the set-command for fixing this per cron :-)

**Comment by cyberfarer** [comment]
@spassig @xet7 

I created a file /etc/cron.d/wekan with the following contents:

0 7 * * * root /usr/bin/snap set wekan mail-url='smtp://localhost:25'
0 7 * * * root /usr/bin/snap set wekan mail-from='CLSA TASK BOARD <no-reply@domain.com'

I use postix as a smart relay to our organizational SMTP server. I found both commands necessary as executing the first replaced the from address with 'wekan-admin@example.com'. 

So far so good.

**Comment by JHAServiceTrace** [comment]
Hi,

I have the same problem: after every automatic Snap update email via the WebUI does no longer work. Saving the email settings without any changes solves this problem. Unfortunately, I have to do this after every Update. As described above, I created a cron tab to re-set the email settings daily (via snap set ...). But this does not affect the WebUI. If I want to invite new users, I have to save the settings at the WebUI before this, otherwise the new users does not get an email notification.

Are the email settings via "snap set ..." related to the email settings via WebUI? Can I solve the WebUI problems with the crontab?


Thanks and regards

   Jochen

**Comment by xet7** [comment]
@spassig @cyberfarer @JHAServiceTrace 

Please test does now `snap set wekan mail...` settings keep working with newest Wekan.

**Comment by JHAServiceTrace** [comment]
Hello,

my current Wekan version is 5.02.0. Now, the email settings in the Admin panel show only the button "Send a test email to yourself". After selecting the button, the error message "... SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332" appears in the web UI. I know this error from previous releases. In the past I could fix this problem by saving the email settings in the Admin panel. Without changing the properties.

Wekan is installed via Snap at an Ubunutu 18.04 host. I searched a lot via Google. Unfortunately, I cannot find an answer to this. 

Regards

   Jochen

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#if-you-get-sslv3-protocol-error

**Comment by JHAServiceTrace** [comment]
Hello,

thank you very much for the fast reply. I tried this settings. Now I get the following error: "Mail command failed: 451 5.7.3 STARTTLS is required to send mail".

Regards

  Jochen

**Comment by xet7** [comment]
@JHAServiceTrace 

Maybe this?
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#wrong-port

Please search that webpage for STARTTLS. Thanks!

**Comment by cyberfarer** [comment]
I have disabled my cron jobs. I will report back tomorrow.

**Comment by xet7** [comment]
@cyberfarer 

Thanks! I'm currently building new Wekan release, so we will then see does it work.

**Comment by JHAServiceTrace** [comment]
Hi,

starting with your following example I changed several parameters and checked the result:
`snap set wekan mail-url='smtp://support%40example.com:password@mail.example.com:587/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'`

We are using Microsoft Office 365. The following parameter set works for me.
`snap set wekan mail-url='smtp://user:password@smtp.office365.com:587?ignoreTLS=false&tls={rejectUnauthorized:false}&secure=true'`

I will change my crontab, respectively.

Thank you very much for your help.


Regards

    Jochen

**Comment by xet7** [comment]
@JHAServiceTrace 

Thanks a lot ! I added your Microsoft Office 365 example to https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
