### ISSUE TITLE
Change backup location via snap without Mongo Shell

### ISSUE THREAD

**Issue by nomomnom** [wekan/wekan-snap#79]
Hey there,

I am using the command
`sudo wekan.database-backup`
to backup our Wekan database on an Ubuntu 18.10 Server. Is it possible to change the directory where the backup is saved in?
Mongodump doesn't work for me, since Mongo Shell isn't installed. And I can't find a way to change the location.

**Comment by xet7** [comment]
You could try backup scripts:
https://github.com/wekan/wekan/wiki/Backup

**Comment by nomomnom** [comment]
>You could try backup scripts:
https://github.com/wekan/wekan/wiki/Backup> 

> Mongodump doesn't work for me, since Mongo Shell isn't installed. And I can't find a way to change the location. >


.....
Managed to make it work, tho.

What is the difference between
`mongodump`
and
`sudo wekan.database-backup`
? Where are the attachements saved?

**Comment by xet7** [comment]
Only difference is that wekan.database-backup compresses backup with gzip, as can be seen at:
https://github.com/wekan/wekan/blob/devel/snap-src/bin/mongodb-backup

All wekan data, including text and attachments, are in database, and in that dump. After you have restored it to MongoDB with mongorestore, you can connect to database with NoSQLBooster (Win/Mac/Linux version) and save attachments to files:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file#12-save-attachments-to-files
