### ISSUE TITLE
snap install wekan - error

### ISSUE THREAD

**Issue by dulhaver** [wekan/wekan-snap#8]
> :~$ sudo snap install wekan
2017-07-17T09:08:32+08:00 INFO cannot auto connect wekan:network-bind to core:network-bind: (plug auto-connection), existing connection state "wekan:network-bind core:network-bind" in the way
error: cannot perform the following tasks:
>- Run configure hook of "wekan" snap if present (run hook "configure": cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied)

my environment is 
> $ snap version  
snap    2.25~14.04  
snapd   2.25~14.04  
series  16  
ubuntu  14.04  
kernel  3.13.0-116-generic`
due to no experience with snap I can not make any sense really from this. Is is a connection problem? Due to being located in China that happens often with such things, so it's my first guess and downloading the snap already is awfully slow  
  
a second attempt returns: 
> error: cannot perform the following tasks:  
> - Download snap "wekan" (21) from channel "stable" (unexpected EOF)
- I managed to install the snap on another test server (running ubuntu 16.04 though) a few days ago.
- I **can** do `snap install hello-world` and also could download the `core` package though, so I think locally snapd is working.

**Comment by vrms** [comment]
a second attempt returns

> error: cannot perform the following tasks:
> - Download snap "wekan" (21) from channel "stable" (unexpected EOF)

**Comment by kubiko** [comment]
Hi
Problem is that snapd has been updated, but kernel version is not aligned with it. You have already new kernel installed on that machine, but it is not running yet, as reboot is required.
One you reboot, everything should be working as expected. If not let me please know

**Comment by dulhaver** [comment]
> Once you reboot, everything should be working as expected

that's it. thanks. Closing
