### ISSUE TITLE
Can't upload file attachment more than 10ko

### ISSUE THREAD

**Issue by benjoco295** [wekan/wekan-snap#80]
Hi everybody,

First, many thanks for this app, it's very nice!

I recently installed the newest version of wekan (2.23) with snap on a fresh centos7 install. I use nginx as reverse proxy. I've enabled ldap. Everythings works except the file attachment with files more than 10ko (I guess).
![test_files](https://user-images.githubusercontent.com/42819163/53129981-524b1000-3569-11e9-9f3c-a7020d9b0e1d.png)
As you can see, little files (~8ko) are successfully uploaded but for others (more than 10ko, ~25ko)  I get a message "user attached null to this card." and I can't do nothing with...

Maybe I miss something in the configuration ?

In advance, thank you.

Regards

**Comment by xet7** [comment]
Set bigger attachement size at `/etc/nginx/nginx.conf`
```
http {
    ...
    client_max_body_size 100M;
}    
```
This is mentioned at Wekan Nginx confix page, there is link to Attachment size:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

Well, now I also added that to example config at that wiki page, it was missing.

**Comment by benjoco295** [comment]
Hi xet7,
Thank you, this solution solved the problem! Also www-data user does not always exist when nginx is installed, so I suggest to set nginx user in nginx.conf

**Comment by xet7** [comment]
@madgics 

Please update above wiki Nginx page directly to have that user setup. Thanks!
