### ISSUE TITLE
Mongo database location

### ISSUE THREAD

**Issue by nomomnom** [wekan/wekan-snap#81]
Hey there,
I installed wekan and mongodb via snap. Unfortunately I am not able to find the directory, we're the database is saved. Everywhere it is suggested to look up the path in the mongodb.conf which is located in
/etc/mongodb.conf
but I can't find that file either.
So how do I know where the config file is saved?

**Comment by xet7** [comment]
Wekan snap backup works with MongoDB 3.21 cli tools:
```
mongodump --port 27019
```
Actual MongoDB database files are are here, but I presume they are not user modifiable:
```
/var/snap/wekan/common
```
MongoDB settings should be set with Wekan snap commands:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys#list-of-supported-keys

**Comment by nomomnom** [comment]
Thank you! This isn't for back up reasons. I've clustered the webserver where wekan is running on, so it is always available, even if one of the webserver crashes. But I wanted to outsource the wekan database on another network drive, so both nodes have access to the same database.

**Comment by xet7** [comment]
@nomomnom 

Then you could:
1) Backup Wekan database
2) Install MongoDB 3.2.21 according to info at MongoDB website for your operating system
3) Configure your mongoDB to have database at external harddrive, using maybe /etc/mongod.conf or similar config, changing path to there directly.
4) Disable Wekan included MongoDB
```
sudo snap stop wekan.mongodb
sudo systemctl disable snap.wekan.mongodb
```
5) Use Wekan snap settings to configure your Snap settings MongoDB URL to your separately-installed MongoDB.

**Comment by nomomnom** [comment]
Thank you really much!! Going to try this soon :)

**Comment by cimm** [comment]
Is there a way to find the broken document in the database?

If I know the broken card I can manually remove it which would hopefully fix my broken board (it's a big board and impossible to move manually).

```
wekan.wekan: MongoError: file with id 5d10eab3d4965208d6153249 not opened for writing
wekan.wekan:     at Function.MongoError.create (/snap/wekan/548/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
tasks wekan.wekan:     at /snap/wekan/548/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
```

How do I find document `5d10eab3d4965208d6153249`? I searched in each of the mongodb collections but couldn't find it. Any ideas?

**Comment by Martan404** [comment]
> 
> 
> @nomomnom
> 
> Then you could:
> 
>     1. Backup Wekan database
> 
>     2. Install MongoDB 3.2.21 according to info at MongoDB website for your operating system
> 
>     3. Configure your mongoDB to have database at external harddrive, using maybe /etc/mongod.conf or similar config, changing path to there directly.
> 
>     4. Disable Wekan included MongoDB
> 
> 
> ```
> sudo snap stop wekan.mongodb
> sudo systemctl disable snap.wekan.mongodb
> ```
> 
>     1. Use Wekan snap settings to configure your Snap settings MongoDB URL to your separately-installed MongoDB.

How would I do this with the non-snap version? I'm trying to get my server running on a Raspberry Pi to store the database files to my external drive. It wasn't really clear in the [guide](https://github.com/wekan/wekan/wiki/Raspberry-Pi#please-store-mongodb-database-etc-wekan-files-to-external-ssd-hardrive-or-hdd).

**Comment by xet7** [comment]
@Martan404 

A)

1. Install MongoDB 4.x

2. `sudo systemctl stop mongod`

3. Edit textfile `/etc/mongod.conf` or similar, it has path to database files, like `/var/lib/mongodb`, change it to new path like `/media/pi/ext/mongodb`

4. Move database files: `sudo mv /var/lib/mongodb /media/pi/ext/`

5. Start and enable mongodb or mongod
```
sudo systemctl start mongod
sudo systemctl enable mongod
```

B) Move while /var to extelnal drive, including /var/log etc etc

1. Stop MongoDB etc services
2. `sudo cp -pR /var  /media/pi/ext/`
3. Edit /etc/fstab so it mounts /var to  external drive /var, or /var as whole external drive. You get UUID from gparted.
4. `sudo rm -rf /var`
5. Mount all drives: `sudo mount -a`
