### ISSUE TITLE
Snap install error: cannot create pipes for commanding the helper process

### ISSUE THREAD

**Issue by derheap** [wekan/wekan-snap#82]
I tried to install Wekan with Snap, but the install fails with the following error:

~~~~
$ snap install wekan
error: cannot perform the following tasks:
- Run install hook of "wekan" snap if present (run hook "install": cannot create pipes for commanding the helper process: Invalid argument)
~~~~

Some Snap info:

~~~~
$ snap version
snap    2.37.2
snapd   2.37.2
series  16
ubuntu  16.04
kernel  4.4.0-042stab134.8
~~~~

Snap changes:

~~~~
$ snap changes
ID   Status  Spawn               Ready               Summary
1    Done    today at 21:29 CET  today at 21:29 CET  Initialize system state
2    Error   today at 21:29 CET  today at 21:30 CET  Install "wekan" snap
3    Done    today at 21:29 CET  today at 21:29 CET  Initialize device
4    Error   today at 21:32 CET  today at 21:32 CET  Install "wekan" snap
5    Error   today at 21:35 CET  today at 21:35 CET  Install "wekan" snap
6    Error   today at 21:40 CET  today at 21:40 CET  Install "wekan" snap
7    Done    today at 21:44 CET  today at 21:44 CET  Install "hello-world" snap
8    Error   today at 21:47 CET  today at 21:47 CET  Install "wekan" snap

$ snap change 8
Status  Spawn               Ready               Summary
Done    today at 21:47 CET  today at 21:47 CET  Ensure prerequisites for "wekan" are available
Undone  today at 21:47 CET  today at 21:47 CET  Download snap "wekan" (436) from channel "stable"
Done    today at 21:47 CET  today at 21:47 CET  Fetch and check assertions for snap "wekan" (436)
Undone  today at 21:47 CET  today at 21:47 CET  Mount snap "wekan" (436)
Undone  today at 21:47 CET  today at 21:47 CET  Copy snap "wekan" data
Undone  today at 21:47 CET  today at 21:47 CET  Setup snap "wekan" (436) security profiles
Undone  today at 21:47 CET  today at 21:47 CET  Make snap "wekan" (436) available to the system
Undone  today at 21:47 CET  today at 21:47 CET  Automatically connect eligible plugs and slots of snap "wekan"
Undone  today at 21:47 CET  today at 21:47 CET  Set automatic aliases for snap "wekan"
Undone  today at 21:47 CET  today at 21:47 CET  Setup snap "wekan" aliases
Error   today at 21:47 CET  today at 21:47 CET  Run install hook of "wekan" snap if present
Hold    today at 21:47 CET  today at 21:47 CET  Start snap "wekan" (436) services
Hold    today at 21:47 CET  today at 21:47 CET  Run configure hook of "wekan" snap if present
Undone  today at 21:47 CET  today at 21:47 CET  Connect wekan:network to core:network
Undone  today at 21:47 CET  today at 21:47 CET  Connect wekan:network-bind to core:network-bind

......................................................................
Run install hook of "wekan" snap if present

2019-02-25T21:47:16+01:00 ERROR run hook "install": cannot create pipes for commanding the helper process: Invalid argument

~~~~

**Comment by Toastgeraet** [comment]
I have the exact same problem, but with the lxd snap.

**Comment by xet7** [comment]
@Toastgeraet 

Does this help?
https://github.com/wekan/wekan-snap/wiki/Many-Snaps-on-LXC

**Comment by Toastgeraet** [comment]
> 
> 
> @Toastgeraet
> 
> Does this help?
> https://github.com/wekan/wekan-snap/wiki/Many-Snaps-on-LXC

Hey there,

Thank you for your reply.
i am sorry, but this doesn't help. My issue is exactly that of 

> error: cannot perform the following tasks:
> - Run install hook of "wekan" snap if present (run hook "install": cannot create pipes for commanding the helper process: Invalid argument)

except that i tried to install lxd, not wekan. Otherwise exactly the same. While this here is the place for wekan issues of course, i think these issues are so extremely similar that solving one might help solve the other.

Btw, i am on Ubuntu 16.04 with the machine in question.

**Comment by xet7** [comment]
@Toastgeraet 

Does your server have limited kernel, like at OpenVZ/OVH/Kimsufi ?

Is it possible for you to upgrade to at least Ubuntu 18.04, or if possible, newest Ubuntu?

**Comment by Toastgeraet** [comment]
> @Toastgeraet
> 
> Does your server have limited kernel, like at OpenVZ/OVH/Kimsufi ?
> 
> Is it possible for you to upgrade to at least Ubuntu 18.04, or if possible, newest Ubuntu?

Yes, and i will upgrade soon and also expect that will solve the issue. Although with the limited kernel you might be onto something. I'll have to look into that.

**Comment by xet7** [comment]
Snap does not work with OpenVZ/OVH/Kimsufi. For those, you can only use Bash/SystemD like mentioned at links at https://wekan.github.io . For limited kernel, updating Ubuntu version does not help, Snap/Docker/Sandstorm does not work propersly.

Snap/Docker/Sandstorm only work on bare metal or full virtualization like KVM/XEN/VirtualBox/VMware (with newest patches) like is at AWS/Azure full linux VM/DigitalOcean/Upcloud.
