### ISSUE TITLE
How to downgrade to 2.43

### ISSUE THREAD

**Issue by Daniel-H76** [wekan/wekan-snap#85]
Since LDAP authentication is broken for several days now (https://github.com/wekan/wekan-ldap/issues/43) and none of our employees is able to work on their tasks anymore, is there any option to revert to version 2.43 to get the system up and running again? Are downloads of older snap files for local installation available?

"snap revert wekan" only switches back to 2.45. 
"snap info wekan" shows no channels for older versions.

**Comment by xet7** [comment]
I will fix tomorrow when I wake up.

**Comment by xet7** [comment]
If you really are in a hurry, use Docker wekan with version tag.
