### ISSUE TITLE
Installed wekan via snap, now what?

### ISSUE THREAD

**Issue by geekmom3** [wekan/wekan-snap#89]
Hello,

I am trying to get Wekan set up via snap on localhost (using Ubuntu 18.04). I followed the instructions and set the port to '80' and the root-url to the IP address that I set in the Vagrant file and hosts file on my machine.

I'm getting the standard apache2 default web page. Wekan does not come up.

I'm new to using snap and read through the documentation on their site as well. 

I don't have caddy installed but wekan and mongodb appear to be up and running:

sudo snap services
Service        Startup   Current   Notes
wekan.caddy    disabled  inactive  -
wekan.mongodb  enabled   active    -
wekan.wekan    enabled   active    -

What am I missing?

**Comment by xet7** [comment]
Did you create Apache config where Apache proxies to Wekan port 3001 ?
https://github.com/wekan/wekan/wiki/Apache

Did you set root-url ?
https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
If you would like to use Caddy with automatic SSL, then you need to stop and remove apache, and edit `/var/snap/wekan/common/Caddyfile` that has example at bottom of that textfile, there change your domain, and then do `sudo snap set wekan caddy-enabled='true'`

**Comment by xet7** [comment]
Snap settings are here:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

And adding users:
https://github.com/wekan/wekan/wiki/Adding-users

**Comment by geekmom3** [comment]
xet7,

Thank you for your response! :)

I'm doing this on localhost and without SSL, since certbot / let's encrypt needs an actual domain (from what i've read while troubleshooting). I set both root-url and the port.

root-url = http://55.55.55.6
port = '80'

Regarding the proxy, do I still need to add this to my Apache config even if I intend to use port 80? I'd like to use Wekan like so: http://55.55.55.6 where Wekan is using port 80.

**Comment by xet7** [comment]
No you don't need apache and caddy etc at all, when you have set wekan to use port 80.
