### ISSUE TITLE
Migrate from wekan-ondra to official wekan

### ISSUE THREAD

**Issue by anlx-sw** [wekan/wekan-snap#9]
Hi Kubiko,

You advised to migrate from wekan-ondra to the official wekan snap.
How can this be accomplished? (sorry if this is already documented somehow - i couldn't find any documentation concerning migration)

Only way i could think of is 
```
snap run wekan-ondra.database-backup
snap run wekan-ondra.database-list-backups
```
copy the backup file to some other place
```
snap remove wekan-ondra
snap install wekan
```
copy the backup back to 
`/var/snap/wekan/common/db-backups/`
`wekan-ondra.database-restore`

is this working  or is there a better way?

**Comment by xet7** [comment]
@anlx-sw 

I think you should restore with:

```
wekan.database-restore
```

**Comment by kubiko** [comment]
Hi
sorry for delay, I was off the grid for some time….
So database restore will sure preserve your database and it's probably good thing to use time too anyway….. But then one has to remember to migrate also all other settings. weak(-ondra).help should print you those you altered.
Alternatively you can see settings stored in:
/var/snap/wekan(-ondra)/common/wekan_settings.sh
Though I'm planning to phase this file out as there is now better and cleaner way to store key-value pairs….

But may be less cumbersome and easier way would be:
$ snap disable wekan-ondra
$ snap install wekan
$ snap disable wekan
$ sudo cp -r /var/snap/wekan-ondra/common /var/snap/wekan/
$ snap enable wekan

- once happy and confident
$ snap remover wekan-ondra

at least till I remove wekan_settings.sh anyway….

**Comment by yogi52** [comment]
Dear Kubiko, Lauri,
1) I just installed wekan-ondra a while ago; is it true that I migrate from wekan-ondra to wekan (xet7) before i go further and further? Is the above procedure still valid anno Oct 2018?
2) I was trying wekan in Sandstorm Oasis where I saw a different very handy feature: notifications with numbers on a notification bell and on the names of members ... is this based on Wekan (xet7) also?
Tnxs and Rgds, Joseph

**Comment by xet7** [comment]
@yogi52 

1. Yes you can backup your wekan-ondra:
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore
And then restore it to wekan (xet7)
https://github.com/wekan/wekan-snap/wiki/Install

2. Moved to https://github.com/wekan/wekan/issues/1256

**Comment by yogi52** [comment]
@xet7 (Thanks) @kubiko 👍 
1) I made a combination of the above recs with the Ubuntu 18.04 Software install/remove facility:
$ snap run wekan-ondra.database-backup
$ snap disable wekan-ondra
Install wekan with Ubuntu Software facility
$ snap disable wekan
$ sudo cp -r /var/snap/wekan-ondra/common /var/snap/wekan/
$ snap enable wekan
Remove wekan-ondra with Ubuntu Software facility

--> 100% migrated without any error (so far)

**Comment by kubiko** [comment]
@xet7 I noticed there is still considerable number of people tracking wekan-ondra
Can you produce version of wekan-ondra which would have on login page warning that this version is no more supported and link to instructions how to migrate.
Is this something you can help me with? I'm not nodejs expert

**Comment by xet7** [comment]
@kubiko 

Another possibility is to push wekan to wekan-ondra too.

**Comment by kubiko** [comment]
we would need to maintain two snapcraft.yaml files, to enable auto builds, which would mean to have two devel branches, which would only differ in name in snapcraft.yaml
Unfortunately snap name is built into snap packages so we can't just push same binary to two places.
And one would need to remember to promote both snaps. Seems like too much work commitment. I'd prefer to wind it down while we can

**Comment by xet7** [comment]
@kubiko 

Ok I'll try to create migration version of wekan-ondra.

**Comment by kubiko** [comment]
@xet7 sounds like a plan, thank you!

**Comment by yogi52** [comment]
Dear both,

It happened that I started earlier with wekan-ondra because both wekan and wekan-ondra occur as Ubuntu packages (16.x) and 18.x) with exactly same information. Maybe it could be advised to offer now only wekan. Cheers Jos

On 15-11-18 12:38, Ondrej wrote:

we would need to maintain two snapcraft.yaml files, to enable auto builds, which would mean to have two devel branches, which would only differ in name in snapcraft.yaml
Unfortunately snap name is built into snap packages so we can't just push same binary to two places.
And one would need to remember to promote both snaps. Seems like too much work commitment. I'd prefer to wind it down while we can

**Comment by xet7** [comment]
@kubiko

Would it be OK for you to transfer ownership of wekan-ondra to me so I could update it with newest Wekan?

https://dashboard.snapcraft.io/register-snap-feedback/wekan-ondra/
