### ISSUE TITLE
Wekan's mongodb.log grows pretty large (unlimited?)

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan-snap#92]
## Issue

I noticed my mongodb.log has grown pretty large:

    root@battra:~# ls -lh /var/snap/wekan/common/mongodb.log
    -rw-r--r-- 1 root root 3,1G touko  4 21:14 /var/snap/wekan/common/mongodb.log

The first lines in the log are timestamped 2018-03-02T16:39:44.754+0200.

Should the log rotate automatically, but doesn't for some reason? Alternatively, should I truncate it manually (and if so, how)? I have no use for the logs apart from the occasional bug reports here, so even losing all of it is fine.

There are no related mongodb settings keys AFAICS. (And sorry if this is unrelated to snap packaging, it was just a guess on my part.)

**Server Setup Information**:

* Wekan version: 2.65
* Operating System: Ubuntu 16.04
* Deployment Method: snap
* Http frontend if any: Apache 2.4

**Comment by xet7** [comment]
Here seems to be related discussion:
https://forum.snapcraft.io/t/best-practice-for-logging/1210/15

Someone could try to find out what should be done to logrotate correctly.

**Comment by uusijani** [comment]
Looks like this is exacerbated by [Wekan issue #1911](https://github.com/wekan/wekan/issues/1911), as it turns out 99,8 % of the log is about the socket connection (since 2018-09-15):

    root@battra:~# grep -c -v "received client metadata from anonymous unix socket" /var/snap/wekan/common/mongodb.log
    23426
    root@battra:~# grep -c "received client metadata from anonymous unix socket" /var/snap/wekan/common/mongodb.log
    10970660

Log rotation would still be nice, but nowhere near as critical if less than one percent of the current logging was produced (a few megabytes per year in my setup here, if I extrapolated correctly).

**Comment by kubiko** [comment]
Two easy options
a) abandon log file all together and use systemd journal for log handling
b) log to SNAP_DATA instead, and start clean log for each revision, once revision is removed old log file goes with it. This will not solve issue when certain revision goes crazy on logging or one revision is active for long, second not really being wekan case

**Comment by rlach** [comment]
While wekan issue 1911 makes this worse it's still unacceptable for log to grow without limit. My log took over whole instance, making snap unable to start properly (I was getting 502 errors when trying to access wekan). I checked first entries in the log and there were from the data I first installed the snap.
