### ISSUE TITLE
Backup failed : libssl.so.1.0.0 error

### ISSUE THREAD

**Issue by Sysdmin** [wekan/wekan-snap#94]
When I try to use the backup script v2 published here : https://github.com/wekan/wekan/wiki/Backup

I have this error :
`/snap/wekan/525/bin/mongodump: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

Openssl is already installed on my server but on version  "1.1.0j-1~deb9u1"

My config :
Debian 9 (up-to-date)
Wekan install with snap

**Comment by xet7** [comment]
That is because mongodump is from Ubuntu-based distro.

You can install mongodump for your distro:
```
sudo apt install mongodb-tools
```
Or install from MongoDB website:
https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-debian/

**Comment by derhelge** [comment]
With Ubuntu 20.04 its `mongodb-clients` i guess...
