### ISSUE TITLE
bash: mongodump: command not found...

### ISSUE THREAD

**Issue by HenryBao91** [wekan/wekan-snap#95]
[root@bim ~]# mongodump --port 27017
bash: mongodump: command not found...

[root@bim ~]# bash wekan-backup.sh

The database backup is in progress.

wekan-backup.sh:行16: /snap/wekan/525/bin/mongodump: No such file or directory

Makes the tar.gz file.
525-2019-06-11_08.59.18/

Backup done.
Backup is archived to .tar.gz file at /var/backups/wekan/525-2019-06-11_08.59.18.tar.gz

**Comment by xet7** [comment]
sudo apt-get install mongodb-tools

Or some similar command for your distro.

Or, search how to install mongodb.
