### ISSUE TITLE
external mongodb replicatset server

### ISSUE THREAD

**Issue by apages2** [wekan/wekan-snap#96]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 2.90 rev 548
* Operating System: centos 7.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache
* MongoDB Version: 3.2.22

**Problem description**:
Hello

I use wekan in snap mode

I would like to use an external mongodb in replicaset mode, but I can not change the MONGO_URL variable with: mongodb: // host1: 27017, hots2: 27017, host3: 27017 / wekan? Replicaset = RS0

how can I do?

best regards

**Comment by xet7** [comment]
Maybe change mongodb port?
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
```
sudo snap set wekan mongodb-port='27019`
```
Or try changing mongo-url:
```
sudo snap set wekan mongo-url='......'
```
If you use some other MongoDB server, you can stop Wekan MongoDB:
```
sudo snap set wekan disable-mongodb='true'
```
Or try Docker.
https://github.com/wekan/wekan/issues/2485

**Comment by xet7** [comment]
Here seems to be same issue #81

**Comment by apages2** [comment]
Hello,

 

the mongo-url key does not exist in the supported-settings-keys and therefore does not work, when i look through ` snap logs -f wekan `, the mongo-url is the inheritance of my mongodb-bind-unix-socket, or mongodb-bind-ip and mongodb-port parameters, but never mongo-url

**Comment by apages2** [comment]
Hello,

I tested several different configuration, but it does not work.

![wekan-mongodb](https://user-images.githubusercontent.com/12720395/60168560-5cc23280-9805-11e9-8494-052d8b6504d7.PNG)

is it possible to add mongo-url in supported-settings-key?

best  regards

**Comment by xet7** [comment]
Yes, it's now added. https://github.com/wekan/wekan/blob/master/snap-src/bin/config#L15
