### ISSUE TITLE
Comment only users can add attachment and archive boards, lists and cards

### ISSUE THREAD

**Issue by dfanaei** [wekan/wekan-snap#97]
Hi, 
I just installed wekan using snap. 
everything is good, except, when I add a user to a board and change the permission to comment only the user still gets to archive boards, lists and cards. they also get to add attachments to the cards.
I think a comment only user must not be able to do any of that. The same issue goes with No comment permission. 

![2019-07-22-at-09-25-06](https://user-images.githubusercontent.com/29267557/61668760-936b5b80-ac92-11e9-91a0-c261af33e115.gif)

Do you know how to fix this? Since Im using snap and am not familiar with Node, I do not know where to go and what to do. Can you help?

**Comment by xet7** [comment]
I do know, but my time is limited. Try:
```
git clone https://github.com/wekan/wekan
cd wekan
./find.sh CommentOnly
```
And try to find where permission is checked. Wekan parts for this are at `wekan/client/components/`. When you find what is missing, please add comment to this issue with links to same code lines at GitHub wekan/wekan by clicking line of code or cose range like `L20-L40`.

**Comment by dfanaei** [comment]
I am not sure if I am quite following you.
Sorry, I am pretty new in everything, I only know how to edit some basic codes as well as running a few commands :). I'm also super new to github. 
however, I ran the commands and the results are listed below:

./client/components/boards/boardHeader.js:      !Meteor.user().isCommentOnly()
./client/components/boards/boardBody.js:        !Meteor.user().isCommentOnly()
./client/components/lists/list.js:        !Meteor.user().isCommentOnly()
./client/components/lists/listHeader.jade:            unless currentUser.isCommentOnly
./client/components/lists/listHeader.jade:          unless currentUser.isCommentOnly
./client/components/lists/listHeader.jade:  unless currentUser.isCommentOnly
./client/components/lists/listBody.js:      !Meteor.user().isCommentOnly()
./client/components/sidebar/sidebar.js:      const commentOnly = currentBoard.hasCommentOnly(this.userId);
./client/components/sidebar/sidebar.js:    const isCommentOnly = $(event.currentTarget).hasClass(
./client/components/sidebar/sidebar.js:      isCommentOnly,
./client/components/sidebar/sidebar.js:      !currentBoard.hasCommentOnly(this.userId)
./client/components/sidebar/sidebar.js:  isCommentOnly() {
./client/components/sidebar/sidebar.js:      currentBoard.hasCommentOnly(this.userId)
./client/components/sidebar/sidebar.jade:            class="{{#if currentUser.isNotCommentOnly}}js-label{{/if}}")
./client/components/sidebar/sidebar.jade:        if isCommentOnly
./client/components/users/userAvatar.jade:      if currentUser.isNotCommentOnly
./models/users.js:    isNotCommentOnly() {
./models/users.js:        board && board.hasMember(this._id) && !board.hasCommentOnly(this._id)
./models/users.js:    isCommentOnly() {
./models/users.js:      return board && board.hasCommentOnly(this._id);
./models/users.js:   * @param {boolean} isCommentOnly only enable comments
./models/users.js:      const { isAdmin, isNoComments, isCommentOnly } = req.body;
./models/users.js:                isTrue(isCommentOnly),
./models/wekanCreator.js:          isCommentOnly: false,
./models/boards.js:              isCommentOnly: false,
./models/boards.js:    'members.$.isCommentOnly': {
./models/boards.js:  hasCommentOnly(memberId) {
./models/boards.js:      isCommentOnly: true,
./models/boards.js:          isCommentOnly: false,
./models/boards.js:    isCommentOnly,
./models/boards.js:        [`members.${memberIndex}.isCommentOnly`]: isCommentOnly,
./models/boards.js:   * @param {boolean} [isCommentOnly] only enable comments (default false)
./models/boards.js:            isCommentOnly: req.body.isCommentOnly || false,
./models/boards.js:   * @param {boolean} isCommentOnly CommentsOnly capability
./models/boards.js:      const { isAdmin, isNoComments, isCommentOnly } = req.body;
./models/boards.js:        isTrue(isCommentOnly),
./models/swimlanes.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/swimlanes.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/swimlanes.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/lists.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/lists.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/lists.js:    return allowIsBoardMemberCommentOnly(userId, Boards.findOne(doc.boardId));
./models/trelloCreator.js:          isCommentOnly: false,
./models/trelloCreator.js:              isCommentOnly: false,
./public/api/wekan.html:  "isCommentOnly": true,
./public/api/wekan.html:<span class="hljs-attr">isCommentOnly:</span> <span class="hljs-literal">true</span>
./public/api/wekan.html:<td>» isCommentOnly</td>
./public/api/wekan.html:      <span class="hljs-attr">"isCommentOnly"</span>: <span class="hljs-literal">true</span>
./public/api/wekan.html:  "isCommentOnly": true
./public/api/wekan.html:<span class="hljs-attr">isCommentOnly:</span> <span class="hljs-literal">true</span>
./public/api/wekan.html:<td>» isCommentOnly</td>
./public/api/wekan.html:  "isCommentOnly": true
./public/api/wekan.html:<span class="hljs-attr">isCommentOnly:</span> <span class="hljs-literal">true</span>
./public/api/wekan.html:<td>» isCommentOnly</td>
./public/api/wekan.html:      <span class="hljs-attr">"isCommentOnly"</span>: <span class="hljs-literal">true</span>
./public/api/wekan.html:  <span class="hljs-attr">"isCommentOnly"</span>: <span class="hljs-literal">true</span>
./public/api/wekan.html:<td>isCommentOnly</td>
./public/api/wekan.yml:        - name: isCommentOnly
./public/api/wekan.yml:        - name: isCommentOnly
./public/api/wekan.yml:        - name: isCommentOnly
./public/api/wekan.yml:      isCommentOnly:
./openapi/generate_openapi.py:            # const {isAdmin, isNoComments, isCommentOnly} = req.body;

**Comment by dfanaei** [comment]
Unfortunately, This setting was a major problem for me. I had to uninstall wekan.

**Comment by xet7** [comment]
I'm reopening this, because this is not fixed yet.

I will fix this in near future.

**Comment by xet7** [comment]
NoComment permission is designed for customers, that do not see comments and activities by expert team responding to issues. So comments and activities are hidden, all else is editable. So I think NoComment permission is OK.

For CommentOnly permission, I will fix those.
