### ISSUE TITLE
 SSL with Caddy  : Link for see details of a card won't use the HTTPS

### ISSUE THREAD

**Issue by zendre4** [wekan/wekan-snap#99]
Hello,
I have try this procedure for activate https :

https://github.com/wekan/wekan-snap/wiki/Install#optional-install-caddy---every-site-on-https 

The ssl is correctly apply by let's encrypt but when I click on a card for see the details, the page is refresh : 

![bug_wekan](https://user-images.githubusercontent.com/9673982/62601708-4c1bd680-b8f2-11e9-84fc-b68cfa5879ba.gif)

I noticed that the html tag are use the old http : 

`
<a class="minicard-wrapper js-minicard ui-droppable" href="http://mydomain.com/b/rq3sJ3EnpbaTzYBtG/myboard/nguoczp6sMRgDubPL">  
`

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='https://wekan.example.com'
```
https://github.com/wekan/wekan/wiki/Settings

**Comment by zendre4** [comment]
Oh I have not see... Thx !
